### ISSUE TITLE
Build failed with Xcode 6.2

### ISSUE THREAD

**Issue by Draveness** [uikit/uikit#1100]
I encounter this problem when building on Xcode 6.2. Is this a problem with Xcode?

    ld: warning: ObjC object file (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/CoreService.framework/Core    Service) was compiled for iOS Simulator, but linking for MacOSX
    ld: framework not found CoreImage for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

    ld: warning: ObjC object file (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/CoreService.framework/CoreService) was compiled for iOS Simulator, but linking for MacOSX

**Comment by vuchl** [comment]
I am not quite sure if you are using the right Uikit package since there is a package named Uikit for [OS X development](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIKit_Framework/) (which I think you only get when you have a developers license?) aswell.

This Uikit right here is a frontend CSS framework and not a OS X Library
