### ISSUE TITLE
Add uk-width-xlarge-x-x

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1139]
Add class uk-width-xlarge-x-x (they are only in grid now) + visibility / hidden class to uk-width-xlarge-x-x (already reported in https://github.com/uikit/uikit/issues/560#issuecomment-90895246)

**Comment by zslabs** [comment]
I think the use-case for this isn't as common as the already in-use attributes available, but what I would like to see is all of these grid-sizes in separate files so we can include what size of the grid-system we require for our project. This way, if there are the common use-case of your size needed, it's easy to plug into the system. cc @aheinze @saschadube

**Comment by saschadube** [comment]
We have plans to add the ```uk-width-xlarge``` classes.

Updating the visibility and hidden classes for the different breakpoints can only be done in UIkit 3 because they would work differently than now and changing it in UIkit 2 would mean to break stuff.

@zslabs Nice idea. Most likely we will also split the Grid component into a gutter and a width component. So we would have gutter, width and flex to rule them all :smile:

**Comment by PixelT** [comment]
@saschadube OK, that's great news - thanks! :)

**Comment by rolandtoth** [comment]
Here is a less mixin to generate custom extra grid sizes:
https://gist.github.com/rolandtoth/f83f6560abd7569ab55f

**Comment by saschadube** [comment]
Done ca903f850c5dd013d7e44ed8832a4ccd0868e227
