### ISSUE TITLE
Offcanvas makes the mainbody flicker in mobile 

### ISSUE THREAD

**Issue by Pandahisham** [uikit/uikit#1147]
I tried safari on ios7 and simulated android on chrome , both were jittery , not smooth , and in ios it flickered for a second before returning to normal

**Comment by florianletsch** [comment]
What exactly do you mean with flickering? When exactly does that happen? 

I can only test iOS 8 right now but can't seem to reproduce that. Are you testing on older devices? Maybe the JS performance causes a lagging behaviour.

Which site are you noticing this on, can you provide a link or a jsfiddle?

**Comment by Pandahisham** [comment]
I browsed the documentation page on my iPhone and found this , when the offcanvas is dismissed , the overlay takes a little bit too much time to get out of the way , causing a flickering appearance , I guess it's hardware stuff . Still worth mentioning  , I will see if I can upload a GIF

**Comment by florianletsch** [comment]
Which iPhone generation are you experiencing this on? I'm on iPhone 5 and it seems to be alright.

**Comment by Pandahisham** [comment]
iPhone 5 iOS 7

**Comment by florianletsch** [comment]
Any specific reason you haven't upgraded to iOS 8? There's actually quite a significant boost in JS performance, so that might just fix the behaviour for you. And the Android simulation is really slow as well.

If you can provide a GIF however we might be able to isolate what exactly you mean with "flickering" and try to improve performance.

**Comment by Pandahisham** [comment]
Guy's I updates IOS and now it's gone , sorry for the false bug
