### ISSUE TITLE
Offcanvas getuikit.com has issues in iOS8 on Iphone 6 Plus

### ISSUE THREAD

**Issue by christianmagill** [uikit/uikit#1203]
I've ran into a strange issue on iOS 8 / iPhone6+

In portrait mode if I open the off-canvas menu  and click on the Compoents>Javascript option, the sub items expand beneath, but I can not scroll to view them all. Additionally, if I open a second section, I am then able to scroll.

**Comment by christianmagill** [comment]
![image](https://cloud.githubusercontent.com/assets/2133370/7362303/ed72ad76-ed34-11e4-9c1d-6d129b1f7ee6.jpg)

**Comment by gornycreative** [comment]
iOS 9 and iPhone 6 has a similar problem. No scrolling on safari when the menu is first opened and the parent item is first expanded. When the menu is closed and reopened with an item expanded, scrolling works.

**Comment by gunderjt** [comment]
I came across a similar problem.  If I open an offcanvas menu and that menu can fit into the screen so that it never overflowed the y axis, then when I expanded a menu element so that the y axis did overflow, the scrolling would not work on the iPhone (Safari)

I had to change the value of overflow-y from `auto` to `scroll`
`.uk-offcanvas-bar {
    overflow-y: scroll;
}`

Hopefully this helps someone.

**Comment by rvalitov** [comment]
Faced the same problem. In my case it happens if:
- I want to use the off-canvas as a mobile side menu
- I put a Nav component inside the off-canvas
- initially the whole content of the off-canvas fits the screen (no scrolling is needed), but when the Nav's elements expands, it becomes too long and requires vertical scrolling. In this situation the scrolling breaks on iPhone and iPad. Reopening the off-canvas can sometimes allow scrolling (for some time, the scrolling can break again any time).

After googling I found out that it's a well known bug with iOS: scrolling breaks inside a div if dynamic content is added which is greater than the height of the wrapper. You can google a phrase "scrolling problem iPhone for div fixed position" and similar. There's a nice article with GIF that shows some scrolling tests http://blog.christoffer.me/six-things-i-learnt-about-ios-safaris-rubber-band-scrolling/

I could solve this problem only by using iScroll http://iscrolljs.com/ I had to add it to the off-canvas.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
