### ISSUE TITLE
HTML Editor with css breaks the parent page.

### ISSUE THREAD

**Issue by HDsign** [uikit/uikit#1249]
Hello,

I'm not sure this component what intended to be used this way, but when I type some css in the html editor it will end up applying the css to the parent page as well. Like in my little examples:

![schermafbeelding 2015-05-10 om 12 28 03](https://cloud.githubusercontent.com/assets/3099122/7553925/a54e726a-f710-11e4-9d0a-1d7cc0794319.png)

![schermafbeelding 2015-05-10 om 12 28 15](https://cloud.githubusercontent.com/assets/3099122/7553927/aa264d4e-f710-11e4-8d4d-83b830238e0c.png)

Is there a way to prevent this from happening? I sure hope so :+1: 

Thanks for the feedback!

**Comment by florianletsch** [comment]
The editor is not inside an iframe, so the css is injected into the regular DOM. So when using general selectors like `body` this changes the global look of the site. This is expected behaviour.

This makes sense if you think of using the editor for a blog post and want to inject that css in the blog post's global CSS.

If you're trying to target something specific, just use selectors less general than `body`.

Hope this answers the question.
