### ISSUE TITLE
These have to be the most confusing install requirements. HELP!!

### ISSUE THREAD

**Issue by jessicahawkins3344** [uikit/uikit#1254]
OK, so I am fairly tired... so cut me some slack, but I am freaking LOST here.

Its tells you to simple install as a bower package as one of the "three" ways to get the uikit.

And directly after those words, its now telling you to clone the whole repo into it's own directory... but wait? What about the browser component I just created... and and btw that browser uikit install is a read only directory I found out! And the dev_uikit theu have up on bower.io doesn't READ the dang bower file.

So - ok, what am I doing wrong or missing. For the claimes of this being very :light weight; I feel like I am just bloating my site up wit duplicate info that is getting me know where. 

WHERE SHOULD THE DIR FILE BE WITHIN AN EXISTING FILE? Node_modules? Bower_components? installing with composer? WHAT!>!>!> This isn't clear at all.

And I really like the demo I have seen. Also, I downloaded some of those yoo demo files... which also make entirely know since to me with multiple config files in ever directory, deep folder linking to what appears to be duplicated content.. and i jjust can't butcher my site like that. K thanks.

**Comment by malles** [comment]
Basically there are several way to handle the UIkit code. How depends on your wishes and skills.
If you don't know what bower is, nevermind and don't use it. Cloning sounds weird to you? Forget it. If you need that, you'd know how to handle it. Compiling your own less overrides to a theme? Huh why? Then don't.
In the basis UIkit is just a CSS and a JS file you add to your site. So that's all you need to have. Download the [zip](https://github.com/uikit/uikit/releases/download/v2.20.3/uikit-2.20.3.zip). You'll find a css, a fonts and a js folder there, that you put somewhere in your site-root, say `/assets`.
You only need to load `assets/css/uikit.css` and `assets/js/uikit.css` on your page. That's it. You're done. Forget the `js/core` folder, never need that. If you want to use a [component](http://getuikit.com/docs/components.html) just add the `assets/js/components/component.js` file, and if exists the `assets/css/components/component.css` file.
The other tools, like Gulp, Less, Bower, Git are very useful for developers, and they will know how to use it. Don't let their presence intimidate you if you don't need them. In the end UIkit is just a CSS an JS file :)

**Comment by malles** [comment]
Oh, the [Get started docs](http://getuikit.com/docs/documentation_get-started.html) basically tells the same story as above. Those are generally easier to read than Git-repo readme-files :)

**Comment by jessicahawkins3344** [comment]
Alright sir. I am going to let you have it just a bit, and I will still blame in fully on my lack of sleep.

I am fully aware of what bower is, its purposes of injecting those dependencies to an asset builder of choice... to compile, appropriately flush through gulp... may I go on? 

I develop on the front end with gulp, bower, bedrock... and all the other great node modules that they come with. News flash, women have the ability to be just as kurt towards men who believe we know nothing.

Secondly, CLONING SOUNDS WIERD TO ME? Man, was that not a sorrry attempt at trying to look superior. And finally I DO NOT WANT the simple css files - as I build use LESS to build my stylesheets  and then use wiredep to minify them. Why would I want to waste so much time?

My questions are simple, and I do not appreciate what I took as very sexist remarks. Additionally, I like to take advantage of the AngularUI instead of having to bloat my docs with so many unnecessary js files. SO - with that being said, I will just figure it out myself. Which I am very capable of... but as I stated, very sleep deprived and was hoping for some help that wasn't so... snooty.

**Comment by jessicahawkins3344** [comment]
And to add, I don't know how anyone couldn't agree that their documentation files are muddled at best. It;s pretty clear since they are constantly asking "How are we doing?!" - "Let us know!". Because it's exhausting really. Not that the package isn't great. However. - G'night!

**Comment by jessicahawkins3344** [comment]
Ok - last one I promise, but I also am not sold on the idea of having to install all of those modules deeper into my project when I have already done that in my project dev which also uses gulp to manage those dependencies so it just looks like its going to take some customization  on my part to minify the docs way down.

**Comment by malles** [comment]
Okay, good luck with that.

**Comment by jessicahawkins3344** [comment]
k... well since you are the ONLY one out there... have you had the trouble of running the bower install uikit --save and its returning with bower no-json       No bower.json file to save to, use bower init to create one

uikit#2.20.3 bower_components/uikit
└── jquery#2.1.4

**Comment by malles** [comment]
That depends on how you manage your bower dependencies. That message is about your local bower.json not existing and has nothing to do with UIkit.
I'm sure that by putting `--save` after the command, you were trying to add UIkit to your dependencies, so you better bower init first to get it going.

**Comment by aheinze** [comment]
thank you @malles for helping out.
