### ISSUE TITLE
Off Canvas + Sticky = Jerky transition

### ISSUE THREAD

**Issue by hansnolte** [uikit/uikit#1262]
With this snippet I could solve my problem with the Navigation.
https://github.com/uikit/uikit/issues/1151

But the Navigation runs rough at back.

Is there a solution against the stutter in the Navigation.

http://www.experimente.bplaced.net/canvas/
(Please resize your Browserwindow)

Thanks in advance
Hans

**Comment by malles** [comment]
I don't see any problems in the animations. Is there a particular device/browser that gives the trouble?

**Comment by hansnolte** [comment]
Hi malles,

thanks for your answer

On the desktop, in a smaller window, the animation jerks strongly when returning.
(Firefox, IE11, Chrome)

On a Smartphone it does not fall on.
See http://www.rpm-factories.de/

**Comment by malles** [comment]
Basing on [this fiddle](http://jsfiddle.net/52umna8c/2/)
I think it is because of the`.uk-offcanvas-page` class is only removed after the transition of offcanvas has ended. Then the sticky is recalculated and the added CSS transition skipped. This hard to do differently, since there is no event firing before the start of the transition.

**Comment by hansnolte** [comment]
Thanks for the explanation!
