### ISSUE TITLE
Fix Undefined variable: "$text-primary-color"

### ISSUE THREAD

**Issue by miladmeidanshahi** [uikit/uikit#1308]
Hello when i want to compile scss files with compass i got this error i change the line of $text-primary-color" to 409 fixed please resolve in core.
```
error sass/framework.scss (Line 410 of sass/_uikit-variables.scss: Undefined variable: "$text-primary-color".)
```

**Comment by k1-hedayati** [comment]
:+1:

**Comment by florianletsch** [comment]
Thanks for reporting. 

What is your file setup (are you importing all files or just specific ones?)

Are you experiencing this on the current version or an older one?

**Comment by miladmeidanshahi** [comment]
it is my file

```
/*========================================
=            Framework Codes.            =
========================================*/

/* compass */
@import "compass";

/* Variable */
@import "uikit-variables";

/* Mixin */
@import "uikit-mixins";

/* Theme */
@import "theme/virtheme";

/* UiKit */
@import "uikit";

/* Components */
@import "components/accordion";
@import "components/autocomplete";
@import "components/datepicker";
@import "components/dotnav";
@import "components/form-advanced";
@import "components/form-file";
@import "components/form-password";
@import "components/form-select";
@import "components/htmleditor";
@import "components/nestable";
@import "components/notify";
@import "components/placeholder";
@import "components/progress";
@import "components/search";
@import "components/slidenav";
@import "components/slider";
@import "components/slideshow";
@import "components/sortable";
@import "components/sticky";
@import "components/tooltip";
@import "components/upload";
```

and i experienced in older version until now.

**Comment by malles** [comment]
I've located the problem.
The variable `text-primary-color` is used by the [contrast component at line 412](https://github.com/uikit/bower-uikit/blob/master/scss/uikit-variables.scss#L412), but declared by the [text component at line 739](https://github.com/uikit/bower-uikit/blob/master/scss/uikit-variables.scss#L739).
The same issue is with the button-component variables used in the contrast component, but that throws no errors, due to the sorting by alphabet.
I've made a fix, but want to see if it is an option to move the `contrast` vars down in the `uikit-variables` file.
