### ISSUE TITLE
Using sass for semantic classnames

### ISSUE THREAD

**Issue by axlf** [uikit/uikit#1318]
Hey,

I have a problem using the sass version and extending my classes for semantic use.

Example:

app.scss
```scss

#container {
  @extend .uk-container, .uk-container-center;
}

.about_us {
  @extend .uk-grid;

  .ce_image {
    @extend .uk-width-1-2;
  }
  .ce_text {
    @extend .uk-width-1-2;
  }
}
```

My HTML Markup
```
<div id="container">
    <div class="about_us">
        <div class="ce_image">
            <img src="http://placekitten.com/g/400/600" alt="" />
        </div>

        <div class="ce_text">
            <h2>Lorem Ipsum</h2>

            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias culpa cum error fugit id minus mollitia, nostrum obcaecati odit omnis provident quae qui quis quisquam quos rem, repellendus sapiente ut.</p>
        </div>
    </div>
</div>
```

The result isn't as expected. The image and the text are placed below each other. But if I write the classnames to the according html tags everything works as expected.

Am I doing something wrong?

Best Wishes

**Comment by florianletsch** [comment]
I'm no sass expert. But could you show the generated css from your sass code?

**Comment by axlf** [comment]
Hey,

here is the gist with the generated CSS

https://gist.github.com/axlf/e63cfc71e31a6275aedd

**Comment by florianletsch** [comment]
Looks like the box-sizing isn't set correctly because the clever selector `[class*='uk-width']` doesn't apply to your semantic class names. That's why some styles needed for the width classes are not applied here.

The short answer is probably that extending uikit's default classes for semantic names is not supported. Long answer is that you can add some css to fix the missing styles, but I'm not sure if that's what you were going for. 

```css
.ce_image, .ce_text {
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  width: 100%;
}
```

Example: http://codepen.io/florianletsch/pen/WvOEEG

**Comment by axlf** [comment]
I saw this at zurb foundation 5 and I find it very useful.

Are you planning to support that style of semantic writing?
