### ISSUE TITLE
Toggle Animation doesn't work correctly, if more than one target is specified

### ISSUE THREAD

**Issue by Riddler84** [uikit/uikit#1339]
Am I misunderstood something or is this a bug? If i click on the toggle, the div-container disappear without animation, but comes back with animation, when i click again.

With only one target specified, it works as expected.

http://codepen.io/anon/pen/VLzooN

**Comment by malles** [comment]
I'm not sure if it's a bug, but you did understand it :)
The problem is in the togglers having a different start-state. One of the icons has the `uk-hidden` class, one hasn't. 
The code checks the group for having the toggle-class: https://github.com/uikit/uikit/blob/master/src/js/core/toggle.js#L72 This always returns true since there will be an element with the `uk-hidden` class. Therefore the 'show' animation is always played.
I made a test that fixes that, see http://codepen.io/malles/pen/WvZepj and https://github.com/uikit/uikit/pull/1341

Now the downside is, that it still does not have the desired behaviour for your purpose, since the buttons you're toggling are now both visible during the animation. Technically it is more exact, but it might break other togglers depending on the current behaviour.

**Comment by Riddler84** [comment]
Thx for the fast answer. Yes, i think this solution isn't the right for my purposes actually.
I think for now i choose a jQuery solution to toggle the icon-classes as you can see here.

http://codepen.io/anon/pen/VLzooN

I'd like to see it working with the uikit toggle in the future, but right now its fine for me. Keep up the good work!
