### ISSUE TITLE
All sortable events not working as the document says

### ISSUE THREAD

**Issue by acaron** [uikit/uikit#1349]
I made a pull request to fix this two months ago: https://github.com/uikit/uikit/pull/1213

All sortable events doesn't work like the documentation says!

**Comment by malles** [comment]
The sortable component is under heavy development at the moment. The event-functions in the options will probably be deprecated, since they are doubles for the `*.uk.sortable` events. 
The event triggers are monitored in the tests, as you suggested in #1213.
At the moment only the `move.uk.sortable` is still broken in the development branch, it is on the todo list.

**Comment by malles** [comment]
The sortable component has been reworked quite a bit now. All events should be as documented now.

Thank you
