### ISSUE TITLE
Question: How do i add background-size parameter from header picture in less???

### ISSUE THREAD

**Issue by NightFalcon650** [uikit/uikit#1373]
In uikit theme for moodle i want tot add a parameter tot the background-image setting.
In wich files and what do i have to change in order to have the uikit theme automatically generate the CSS files through less??

**Comment by zslabs** [comment]
What is moodle? Your question honestly sounds more like a general "how does Less" work question, rather than specific to UIkit. I'd take a look at the [Less docs](http://lesscss.org/) to help you get started and then [this tutorial](http://getuikit.com/docs/documentation_get-started.html) from UIkit to bring all of your Less knowledge together to working with the framework.

**Comment by NightFalcon650** [comment]
Moodle is a LMS. http:\\moodle.org

I've allready looked at different sites,but after two weeks i'd love to have the sollution zo i could film in the rest of the site.

**Comment by zslabs** [comment]
Again - your question doesn't sound like it has anything to do with UIkit specifically, more a general Less question, so I don't believe this is the right medium for this type of question.
