### ISSUE TITLE
Additional Plugin for Lightbox 2.22.0

### ISSUE THREAD

**Issue by JoPhiAT** [uikit/uikit#1495]
Hello,
I'm not very affine with JavaScript, but I need an additional Plugin for Lightbox 2.22.0. I want to use a standard image (e.g. a speaker-symbol) and when the lightbox opens, it should show the html5 audio-player with the controls and it should work for mp3-files (because all major browsers will support this format).

It's not really an issue, but I'm not sure where I can ask else. But maybe this could also be a nice additional feature for all. 

Thanks a lot,
JoPhiAT

**Comment by zslabs** [comment]
Hi,
On http://getuikit.com/docs/lightbox.html at the bottom you'll see an **Events** section that has a JavaScript trigger you could use to implement functionality once an item was shown. If you're not too strong in JS, then you'd want to get with a JS developer that can help you further with this. This isn't something I see being added to the core because while your usecase is interesting, I'm not sure if that speaks to a larger audience and would cause bloat for those that don't need it.

**Comment by JoPhiAT** [comment]
Hi,
thank you very much for your reply and the tips. All options are open, let's get stronger :)

**Comment by malles** [comment]
The lightbox has its own plugins that handle the content. Here an example of an iframe handler:
http://codepen.io/malles/pen/vEQgME
You could make similar for your case.
