### ISSUE TITLE
Problem with uk-grid-* on iPhone Safari after Gulp-Sass or Gulp-Less

### ISSUE THREAD

**Issue by p-h-i-l** [uikit/uikit#1586]
Hi guys, 

i have a problem where uk-grid elements and everything that is inside them don't show up on Safari for IOS 8.3. 

The css `uikit/dist/css/uikit.min.css` works, therefore the content is visible.
The precompiled Version has some bugs. For example *links* from a `uk-block-primary uk-contrast` have a different color. 

I believe it's a problem with preprocessing.
I got my  `.less` and `.sass`  files installed according to this guide and don't get any errors.
I tried gulp-sass and gulp less for preprocessing.

http://getuikit.com/docs/documentation_less-sass.html  

    //compile main.css 
            gulp.task('sass', function() {
              gulp.src(['web/assets/scss/main.scss']) // Gets the main.scss file
                .pipe(sass().on('error', sass.logError)) // Passes it through a gulp-sass task
                .pipe(autoprefixer("last 3 version","safari 5", "ie 8", "ie 9")) // Passes it through gulp-autoprefixer 
                .pipe(csscomb()) // pass through csscomb()
                .pipe(concat('main.css'))
                .pipe(gulp.dest('web/assets/css')) // Outputs it in the css folder
                .pipe(rename({ suffix: '.min' }))
                .pipe(sourcemaps.init())
                .pipe(minifyCss())
                .pipe(sourcemaps.write())
                .pipe(gulp.dest('web/assets/css')) // Outputs it in the css folder
                .pipe(livereload());
            });

and 

         @import "../uikit/dist/scss/uikit-mixins.scss";
		.uk-nav-sub > li > a:focus, .uk-nav-sub > li a:hover {
		    background: #F5F5F5;
			color: #444;
		}

		.uk-nav-sub > .uk-active {
		    background: #F5F5F5;
			color: #444;
		}

		@import "../uikit/dist/scss/uikit.scss";
		@import "../uikit/dist/scss/components/autocomplete.scss";

**Comment by florianletsch** [comment]
This is probably related to auto prefixer. 

I remember a similar issue a while ago. If I remember correctly it was related to different behaviour of the flex layout if you add the `-webkit-` prefix. That is why the uikit code does not include the prefix for the grid on purpose. When you use autoprefixer, this will break.

Please try disabling autoprefixer, everything should already be properly prefixed in the core less/scss. If you want to use autoprefixer for your own styles, maybe split your scss files so that you only apply it on your own code.
