### ISSUE TITLE
Off-canvas flip has a blank between body

### ISSUE THREAD

**Issue by CodinCat** [uikit/uikit#1614]
umm.. just check this codepen: http://codepen.io/anon/pen/YyBzba

![ashampoo_snap_2015 11 15_15h40m58s_001_](https://cloud.githubusercontent.com/assets/3193344/11167856/9a4d5fdc-8baf-11e5-8e23-65e8103afae6.png)

It looks like a scroll bar, and only happens when there is a scroll bar

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/3193344/11167894/fcd5f2c6-8bb0-11e5-9c75-553f484a316b.gif)

how can I remove that? is it a bug?

**Comment by aheinze** [comment]
which browser do you use?

**Comment by CodinCat** [comment]
Tested in Chrome, Firefox and IE 11 in Windows 8.1.

and it also happens in Mac when a mouse is plugged in (the scroll bar will show)

**Comment by TomS-** [comment]
Hello, 

This is mostly a windows 8 problem, however can be fixed by setting .uk-offcanvas-page width to 100%. 

@aheinze, You may be able to answer me this, why isn't .uk-offcanvas-page 100% by default? setting the width in my experience causes problems, especially when resizing the browser with the offcanvas bar open. However width 100% seems to remedy that.

**Comment by lukashl** [comment]
in Chrome do not work

**Comment by unusec** [comment]
add this style: 

::-webkit-scrollbar {
	width: 0px;
}

if will remove the scrollbar on chrome. opera and prolly others but I kinda like the page without the scroll :)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
