### ISSUE TITLE
Autocomplete and GeoNames JSON

### ISSUE THREAD

**Issue by gabyferman** [uikit/uikit#1641]
Hi,

I'm trying to use the GeoNames data to create an autocomplete that shows cities, postal codes & states, but I can't seem to make it work.

First I tried with: `data-uk-autocomplete="{source:'http://ws.geonames.org/searchJSON?featureCode=PPLA2&country=US&adminCode1=CA&username=gabyferman'}"`

but it didn't work, after that I tried to work with the examples in here http://codepen.io/malles/pen/qEyEZr and using `$.getJSON` or `$.ajax`, but I couldn't make it work.

Is there anyone that has use the autocomplete with GeoNames?

Here is the url I would like to use: http://ws.geonames.org/searchJSON?featureCode=PPLA2&country=US&adminCode1=CA&username=gabyferman

**Comment by gabrielholley** [comment]
Your issue is likely that the browser is blocking the request to the URL. Check your console for Cross-Origin Request Blocked or something similar.

Furthermore, the data on your URL is not formatted for the autocomplete component. http://getuikit.com/tests/components/_autocomplete.json

The likely place you need to start to get this working is to setup a server side implementation.

**Comment by entonbiba** [comment]
@gabyferman use http://www.json-generator.com/ to host test json files, it will work on codepen.io and no cross origin blocking.

here is my example:
http://codepen.io/entonbiba/pen/xONPbr

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
The AutoComplete component has not been released yet but we are working on that, please let us know if the problem when it is released for UIkit3.

Thanks for your understanding,
Your UIkit Team
