### ISSUE TITLE
'bug' offcanvas with sticky navbar (Version 2.24.2)

### ISSUE THREAD

**Issue by AlexandreZaytsev** [uikit/uikit#1651]
![image](https://cloud.githubusercontent.com/assets/16114000/11596454/2eaffd22-9ac6-11e5-96f4-bed97c3faffd.png)

**Comment by PixelT** [comment]
+1

**Comment by TomS-** [comment]
If I recall correctly, using 

left: auto !important; on that element will fix this. 

This has been there since I've used UIKit, it's because sticky can be used in columns and therefor needs a left value. 

I would however class this as a bug as everything should move on offcanvas. I can do a push request to fix this. However push requests rarely get added.

**Comment by AlexandreZaytsev** [comment]
ok
