### ISSUE TITLE
AJAX content flicker with data-uk-observe

### ISSUE THREAD

**Issue by jamespatterson** [uikit/uikit#1796]
This is probably by design in the code, but I am looking for a way to eliminate the FOUC that occurs between when I insert AJAX content and before the `data-uk-observe` attribute and mutation observer can fix up the UIkit components.

I have tried calling `UIkit.Utils.checkDisplay($content)` and `$.UIkit.Utils.checkDisplay($content)` before and after inserting the nodes into the DOM, and I still get the flicker. If I remove `data-uk-observe` nothing gets initialized, so I must be calling the wrong method to manually initialize the UIkit components.

Can the flash/flicker be eliminated manually or by an alternate approach with `data-uk-observe`? To be clear, the flicker _only_ happens with the UIkit components. All of the other content replaces seamlessly as if only the exact changes occurred from the user's POV.

**Comment by jerry1970** [comment]
What is data-uk-observe and where do I find it in the documentation??

**Comment by vuchl** [comment]
http://getuikit.com/docs/documentation_javascript.html#dom-observe

**Comment by jerry1970** [comment]
Thanks! Wow, another showcase of how the structure of the documentation could use a bit more thought or more cross-referencing...

**Comment by krajniol** [comment]
We are experiencing the same problem in my company's product, especially in IE11. The perfomance is **ULTRA POOR**. Our customers cannot accept that.

The views where the biggest problems appear is where a lot of content is created dynamically in the DOM. 

What I tested is that there is a change after v 2.24.2 (works smooth) with dom observers which is a total crap.

Our product is built on top of AngularJS and so far the performance was good. We use UIkit since 2014 in several projects and we selected UIkit over foundation/boostrap, because it was lighter and caused less problems. Since year we are observing that this framework is heading into strange direction and the authors are not aware of how to build SPA applications.

**Comment by malles** [comment]
The loading of the components have changed in version 2.26.2. The `data-uk-observe` attribute is no longer needed, nor is initialization in eg angular apps.
Could you please try and test if that improves matters?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
