### ISSUE TITLE
Offcanvas and Navbar not working

### ISSUE THREAD

**Issue by bvelte** [uikit/uikit#1875]
Hi there,

I followed the instructions at "Off-canvas and mobile navigations" (https://youtu.be/MfdMfobt3l4) and have exactly that code to get offcanvas toggle and a basic navbar.
But none of it works. I can see the toggle but nothing happens when I click it. Additionally the navbar is not working, it just shows the li as a word together without any nice layout.

I loaded the uikit.min.js, jquery.min.js and uikit.almost-flat.min.css.
test page: mws.benjaminvelte.de

Please help my, I don't know why its not working. console doesnt show any error and all classes are loeaded but seems to have no influence...

**Comment by brysont** [comment]
Experiencing a similar issue with an offcanvas navbar. Works perfect in Chrome and FireFox on Win10, whether using dev tools for responsive tests, zooming to 300+, or resizing the browser window. Does not work in Chrome on Android 6. Tap the toggle and nothing happens but a brief highlight (a:active state).

Getting no errors on desktop and it shouldn't because it works great there, where it's not actually used. using with JQuery 2.2.3, on PHP 7 within a twig template for Bolt CM. Have nothing but the header in the code right now (porting a theme).

Any known issues? Any advice for troubleshooting a mobile feature that only works on desktop?

Thanks.

**Comment by brysont** [comment]
Actually, the full active or focus state applies to the toggle as if the offcanvas menu is showing, but it never shows. Tapping on the screen to "close" the offcanvas menu changes the toggle state as if it's closing. Testing this on a LG G Stylo with Android 6, Chrome browser. The offcanvas works fine on the phone/carrier's default web browser (MetroWeb).

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
