### ISSUE TITLE
add to grid 1-7 - 1-9

### ISSUE THREAD

**Issue by triooleg** [uikit/uikit#1900]
[uikit-addon-grid.css.zip](https://github.com/uikit/uikit/files/298986/uikit-addon-grid.css.zip)
add to the grid 1-7 - 1-9
I finished the stylesheet

**Comment by julianotheiss** [comment]
+1

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Nut these classes have not been added to the new grid, since these are kind of hard to combinate with other widths are pretty specific.

Thanks for your understanding,
Your UIkit Team
