### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by Fiskoso** [uikit/uikit#1908]
Sorry, but i can't find anything to my issue

i try to use the icon featur of uikit on buttons, but somehow it doesnt seem to work, i only get boxes. i have no idea where the problem comes from
![unbenannt](https://cloud.githubusercontent.com/assets/19840146/15934481/0a8b818c-2e64-11e6-94f5-4262a2bbf416.PNG)

**Comment by C-Lodder** [comment]
Are you using the same directory structure as UIkit when you download the package?
```
root
  --- css
  --- fonts
```

If not, then you will need to modify the path of the fonts in the (S)CSS

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 
In UIkit3 this shouldn't be a problem anymore since we are using our own SVG icons and no font anylonger.

Thanks for your understanding,
Your UIkit Team
