### ISSUE TITLE
Tooltip is too simple

### ISSUE THREAD

**Issue by zhaoyao91** [uikit/uikit#1977]
if the content is too long, it will overflow outside the page, but not wrap correctly.

**Comment by dobaniashish** [comment]
Tooltips are not meant to be long. I dont think thats an issue because dev's have given an option to add your own class. Still, If you want to show long tooltip, you can give a class to your tooltip and add max-width to 100%. For wrap issue you can add word-break: break-all;

Add class 'my-tooltip':
`data-uk-tooltip="{cls:'my-tooltip'}"`

CSS for 'my-tooltip':
`max-width: 100%;`
`word-break: break-all;`

**_Note: The word-break property is not supported in Opera 12 and earlier versions._**

Hope this helps.

**Comment by zhaoyao91** [comment]
@dobaniashish thanks, this does help a lot.
