### ISSUE TITLE
Slideshow component using advanced transition effect: bug when it ends the cycle of slides

### ISSUE THREAD

**Issue by PhoenixII** [uikit/uikit#2053]
Using the slideshow component with any advanced transition effect (slideshow-fx.js), click navigation 'next' to view all the slides. All the things go right until it reaches the last element. If you try to go 'next' again, then it freezes or it becomes blank. You have the same behaviour with 'previous' navigation.
You don't have this behaviour without the advanced transition effects.

To reproduce it, use any of the example of the documentation : https://getuikit.com/docs/slideshow.html#animations
or use this : http://codepen.io/thephoenixii/pen/ORxbwr

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. I can see that error occurring on the slideshow page, here it works for me. 
Since the slideshow component has not been released yet, please let us know if the problem is also there when it is released for UIkit3.


Thanks for your understanding,
Your UIkit Team
