### ISSUE TITLE
Tabs with dropdowns

### ISSUE THREAD

**Issue by ccdiego5** [uikit/uikit#2076]
Hi I'm trying to use the Tabs with dropdowns, and this works fine in large screen but in mobile view doesn't work :-1:  

here the screen when you push the button the Dropdown is open after the click

![dropdownscreen](https://cloud.githubusercontent.com/assets/3355599/19236315/18d62476-8ecd-11e6-8424-18b4dd76db0d.jpg)

but into the mobile view doesn't work, dont show the dropdown items 

![dropdown](https://cloud.githubusercontent.com/assets/3355599/19236356/3187ab0c-8ecd-11e6-9a05-90a7b76d8d53.jpg)

**Comment by shaivyaaggarwal** [comment]
Hi, I think that might be a problem because the page was not loaded properly. 

I tried opening the link in three different browsers in mobile and it works fine.

![image](https://cloud.githubusercontent.com/assets/12891914/19517373/79e8cbe4-961e-11e6-9f62-e1708920f016.png)


![image](https://cloud.githubusercontent.com/assets/12891914/19517379/850ff9a2-961e-11e6-80d2-65339a86e2ce.png)


![image](https://cloud.githubusercontent.com/assets/12891914/19517382/8cce2a06-961e-11e6-8f5a-6e2babb0d783.png)

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team
