### ISSUE TITLE
Uncaught TypeError: Cannot read property 'easeOutExpo' of undefined

### ISSUE THREAD

**Issue by dagatsoin** [uikit/uikit#2085]
**Version:** 2.27.1

this minimal exemple outputs this console.error: `Uncaught TypeError: Cannot read property 'easeOutExpo' of undefined at uikit.js:1386`

But the slideset is working.

```
<!DOCTYPE html>
<html lang="en-gb" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="./css/uikit.css">
    <link rel="stylesheet" href="./css/components/dotnav.css">

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
            integrity="sha256-/SIrNqv8h6QGKDuNoLGA4iret+kyesCkHGzVUUV0shc=" crossorigin="anonymous"></script>
    <script src="js/uikit.js"></script>

    <script src="js/components/slideset.js"></script>

    <title>Index - UIkit tests</title>
</head>

<body>


<div data-uk-slideset="{default: 1}">
    <div class="uk-slidenav-position">
        <ul class="uk-grid uk-slideset">
            <li>...</li>
            <li>...</li>
        </ul>
        <a href="" class="uk-slidenav uk-slidenav-previous" data-uk-slideset-item="previous"></a>
        <a href="" class="uk-slidenav uk-slidenav-next" data-uk-slideset-item="next"></a>
    </div>
    <ul class="uk-slideset-nav uk-dotnav uk-flex-center">...</ul>
</div>
</div>

</body>
</html>
```

**Comment by edurenye** [comment]
This error happens because you are using the slim version of JQuery, use the minified and it will get away.
With slim version there is also other problems like the lightbox not working at all.
I think slim throws effects, so I think it's difficult to offer support for it. Is it even possible to add support for it? Do you want a do it? This issue should be more about this questions IMHO.
The thing is that sometimes you need to use the slim to work with other JS framework like AngularJS or ReactJS.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
