### ISSUE TITLE
Forms in modals

### ISSUE THREAD

**Issue by psuplat** [uikit/uikit#2164]
It would appear that certain form elements, checkbox & radio to be exact, do not work properly when placed in a form that is inside a modal.

You can select only one radio or checkbox. Taking checkbox as an example, once you tick any box that's it, you cannot uncheck it or check any other boxes on that form.

If I cut and paste the exact same form out of modal onto the main page content, it all works as normal.

Did anyone created a modal with multiple radio/checkboxes that works? I cannot see anything wrong in my markup, and firebug does not report any errors.

**Comment by jerry1970** [comment]
I am having problems with getting a checkbox work in a form on a modal when trying to set the value with Vue.js. All examples from the Vue community don't work. It's like a listener is removed as soon as the modal is shown or the listeners are unreachable due to an extra listener that stops propagation of the event.

Also, setting a datepicker (XDSoft's datetimepicker) on a text field doesn't work when the text field is on a modal. I have to set the datepicker (`jQuery('input.datepicker').datetimepicker(dtpOptions);`) every time after showing the modal.

Also setting a listener using jQuery on the Submit button in a modal doesn't work after showing the modal. I've solved this using Vue's `@click` attribute (which is actually better than using jQuery because it's more Vue and less jQuery and I am moving towards Vue).

I am too busy to check out what is going wrong and the workaround is OK for now, but I do wonder what is happening with the listeners when on a modal.

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue. 

Thanks for your understanding,
Your UIkit Team
