### ISSUE TITLE
Offcanvas menu animations are janky

### ISSUE THREAD

**Issue by lukehutch** [uikit/uikit#2199]
Offcanvas menu in/out animations are janky, even on a fast desktop machine. I have seen this in a lot of other offcanvas menu implementations, and it is caused by animations being performed in Javascript, rather than by using CSS transitions, and/or by using non-hardware-accelerated CSS transforms. (I didn't look at the UIkit implementation to see what the exact cause was.) I'm using Chrome on Linux.

See some of the suggestions here (re. adding `transform3d`, `backface-visibility: hidden` etc.):

* https://scotch.io/tutorials/off-canvas-menus-with-css3-transitions-and-transforms
* https://www.smashingmagazine.com/2013/01/off-canvas-navigation-for-responsive-website/

However, re. `transform3d` specifically, see the following, which apparently caused issues for Jasny Bootstrap when they tried to accelerate their off-canvas menu:

* http://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/
* https://github.com/jasny/bootstrap/issues/186

**Comment by zzseba78** [comment]
Offcanvas menú can be better, that´s right, but use css transitions already, triggered by js.
I think the problem it´s that , apart from the offcanvas bar, the **whole html gets animated** ( instead of a content wrapper ), and the property animated it´s **margin** and **clip** ( on reveal mode ) , causing Browser repaints and reflows, instead it should use css transitions and opacity only.

**Comment by lukehutch** [comment]
Using the Chrome Dev Tools' Timeline panel shows a very irregular framerate. I'm not an expert in reading the results of this tool, but every time there's an animation frame, two events (pointermove and mousemove) are generated, which calls into jQuery. Probably the entire document should have these two events disabled before the animation starts, and re-enabled at the end of the drag.

Also, every frame goes through these steps: Recalculate Style, Layout, Update Layer Tree, and Hit Test. Every other frame does Paint and Composite Layers. Definitely there is room for improvement here.

Are the current animations 2D or 3D? The fastest mechanism is supposedly 3D with a 2D fallback, as shown in the links in the original bugreport.

**Comment by zzseba78** [comment]
Like some of the Greensock team member says, use the best tool for testing animations performance... your eyes.
It doesn´t looks soft and fluid, and you are right, i think there is room for improvement here.

**Comment by giorgiobeggiora** [comment]
Any news about this? Thanks.

**Comment by saschadube** [comment]
Off-canvas was refactored in Beta 19 https://github.com/uikit/uikit/releases/tag/v3.0.0-beta.19

How is it performing now? That's the best we could do.

**Comment by lukehutch** [comment]
@saschadube It's still very janky in Beta 22 (which appears to be what is running on the documentation site), both on mobile and on desktop. Even running on my fast desktop machine (8 core / 16 thread Ryzen 1800X, with a recent NVIDIA card, using the closed-source NVIDIA drivers), the offscreen menu demos show frame times of anywhere between 16.6ms to almost 60ms per frame (which causes major hiccups). Even the 16.6ms time per frame is too long, since that is the total rendering time, not including the time gap between frames, so you can't hit the 16.6ms budget per frame to animate at 60fps. The max framerate ends up being 30fps, frequently stuttering to 5-15fps.

However, the browser can easily run hundreds of CSS animations at once at 60fps, so I don't understand why this particular animation is so time-consuming, or why the framerate is so irregular.

Here's a screenshot of the animation, being rendered in Chrome Developer Tools. You can see the frame times near the top, with green background:

![profiling-screenshot](https://cloud.githubusercontent.com/assets/811305/26097882/e38b235c-39da-11e7-99d7-b848d11d0908.png)

It looks like most of the time is being spent in GPU rendering, which is surprising. Probably it would be worth it to look in detail into what the GPU is doing during that time. You can do this by going to about:tracing in Chrome, and enabling the GPU options, then closing all tabs and windows but the one you're interested in, and running a trace while sliding the menus in and out. (Unfortunately I'm about to leave on an overseas trip, so I don't have time to dig further right now..)

Probably though the answer to why the animation is janky is contained in [this blog post](https://medium.com/outsystems-experts/how-to-achieve-60-fps-animations-with-css3-db7b98610108). ([Followup post](https://medium.com/outsystems-experts/flip-your-60-fps-animations-flip-em-good-372281598865))

Also, there are other tips in the links I posted earlier on how to improve performance (e.g. by removing backface rendering, by enabling 3D transforms with a fallback to 2D transforms, by setting the z-order, etc.)

As a stop-gap, you can hide some of the jankiness by doubling the speed of the animation (the animations are too slow right now anyway, in my opinion).

**Comment by zzseba78** [comment]
Do you see that the Offcanvas Overlay mode perform better?
The rule in fact it´s quite simple, **animate only transform and opacity properties**, modern browser manage this quite well. So, for example, instead of animate left, you should use translateX.

I don´t know why, offcanvas in reveal and push mode don´t use transforms, they animate position intead, and this cause the re-paint. The overlay mode use transforms ( translateX ), and looks softer.
There must be a reason why you can not use transforms, one might not play well with other elements (sticky for example), or maybe it makes it difficult to do in the same markup 3 different modes of Offcanvas. UIkit have a great animation component and it uses transforms all the way, so there must be a reason.

**Comment by lukehutch** [comment]
Exactly. Either you have some Javascript handler code that is being triggered during the animation, or you have some derived  properties that are being recompiled as translation is changing, or you are trusting layout. But yes, just affecting translation and opacity should be much smoother than this. 

The overlay:true version in the docs looks just as janky to me as the non-overlay version.

**Comment by zzseba78** [comment]
Sorry, i mean the "Slide" Mode, where the content doesn´t animate ( linke in Reveal or Push mode ), only the offcanvas bar.

**Comment by lukehutch** [comment]
Slide is no better. The modes all have equally uneven framerates.

**Comment by lukehutch** [comment]
If you can't directly see the stuttering leaping out at you (people's temporal perception abilities vary -- I can't not see it), then you should be able to see the effect by opening the Chrome Developer tools (Ctrl+Shift+C) and switching to Performance, then taking a recording while sliding the menu in and out.

**Comment by zzseba78** [comment]
One question, how do you see the performance of the offcanvas menu in the awwwards website.
https://www.awwwards.com/
Looks smooth to the eye.

**Comment by lukehutch** [comment]
That site is pretty smooth to the eye, yes, although it is animating at 30fps, not , because the frames don't fit into the 16ms budget. However, the frames consistently take about the same amount of time to animate, about 17ms, or 20ms with the inter-frame interval (whereas that is not true on the UIkit docs site, with frame times typically taking 20-24ms, but rising to almost 60ms every 5-10 frames or so). If I open/close the menu a few times on awwwards.com, I do see the occasional hiccup (dropping to 15fps or something, for a frame or two), but generally it's pretty consistent.

The thing about the awwwards.com site though, looking at it in Dev Tools, is that it spends quite a lot of time in each frame recalculating styles, and recalculating the layer tree. There must be a complex set of stylesheets and/or layers on the site. But the other thing that is not optimal is that the animation triggers mousemove events during each animation frame, because the canvas is moving under the mouse pointer. One optimization for desktop browsers would be to temporarily remove mousemove event handlers during menu open/close.

**Comment by zzseba78** [comment]
@lukehutch @saschadube  Please tell me how you see this examples i made in terms of performance and of course your eye opinion. My js knowledge it´s poor, so of course uikit team will improve this, i just want to show the concept.

All animations are 3d with 2d fallback, transitions and opacity, also will-change it´s implemented.
Same markup, a container ( offcanvas and content inside ), the offcanvas it´s outside, css have some small variations from one mode to another.

I tested it and looks soft on mobile, ipad and pc. 
**The main problem it´s how to deal with fixed headers.** I will dig into this, because i see some implementation that fix this issue.

Of course any feedback it´s appreciated, also it´s good to know any browser issue that may have.

Push:
https://codepen.io/zzseba78/pen/wdEWRG

Reveal:
https://codepen.io/zzseba78/pen/dWqXvg

Swipe:
https://codepen.io/zzseba78/pen/PmdzLP

**Comment by lukehutch** [comment]
@zzseba78 This does look smooth to me, and the Chrome Developer tools indicate that the framerate is consistent at ~16.7fps, and approximately VSYNC-aligned. However, at wide screensizes (2560x1600), There is noticeable visual tearing, so the frame rendering is split across two visual frames. (This is probably Chrome's fault...)

**Comment by janschoenherr** [comment]
This seems to have resolved itself.
