### ISSUE TITLE
In dark theme, can't read text in comboboxes

### ISSUE THREAD

**Issue by lukehutch** [uikit/uikit#2200]
On this site, if Dark theme is selected, and then a combobox at the top is clicked, the combobox text is not visible (the foreground and background text is rendered in the same shade of gray). Mousing over a line of text in the combobox shows one line at a time.

https://getuikit.com/assets/uikit/tests/index.html

**Comment by saschadube** [comment]
The Dark/Light select box just adds ```uk-dark``` or ```uk-light``` to the ```body``` element. This will of course "destroy" the style of the Navbar, sections (primary + secondary) and cards (primary + secondary) because they already color their own content automatically.

You won't set the ```uk-dark``` or ```uk-light``` classes to the ```body``` element if you use one of these components. You set the classes only for elements which needs them.

In the tests the Dark/Light select box is just for faster testing.

Did my answer help understanding it?

**Comment by lukehutch** [comment]
Yes, although the purpose of the test page is to view a bunch of elements that are supposed to work with a given theme setting, so maybe you should shim this and comment it in the test source. It is highly likely that I'm not the last that will think this is a bug.
