### ISSUE TITLE
Missing width divisions

### ISSUE THREAD

**Issue by philmarty** [uikit/uikit#2209]
Hello,

I think it could be more comfortable to have more possibilities with width components.
It would be nice to have possibility to divide into eighths (1-8) ( 12.5% parts) or tenths (1-10) (10% parts) in order to be more precise when distributing content.

Thanks !

**Comment by svjansen** [comment]
You could copy a few styles from uikit v2

```
/* Tenths */
.uk-width-1-10 {
  width: 10%;
}
.uk-width-3-10 {
  width: 30%;
}
.uk-width-7-10 {
  width: 70%;
}
.uk-width-9-10 {
  width: 90%;
}
```

**Comment by philoest** [comment]
In most the cases 1-8 or even 1-10 are pretty small on screens that was the reason we haven't added them. If you are using 10 items in a row you also can use the `uk-width-expand` classes, since this will set all the items to the same size. If you want to have one small item and a large one you could also consider to use one of the fixed width classes in addition to uk-width-expand. 

If all of this doesn't work for you, you have to copy that from UIkit2 as @svjansen already mentioned

**Comment by philmarty** [comment]
Well, well. In fact it is not for small parts that these subdivisions are interesting, but for the possibility they offer in cutting blocks with more acute proportions.
For example with 1-8 divisions, I can make a 3-8 which is equal to 37,5%, impossible with other cuts, and 3-10 is the same idea.
And, yes, you're right, we can also customize everything if needed. 
But is it the goal of a framework like uikit? ;)
