### ISSUE TITLE
Dynamic Slideset

### ISSUE THREAD

**Issue by maxjf1** [uikit/uikit#2212]
I want to make a dynamic slideset. I tried the uikit observer and init the component manually, but i can't update the slideset when i change the number of itens. Is there a way to make it support and update when i change the number of itens?
this happens with slideshow too, and many other components.

**Comment by philoest** [comment]
Since we have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. 

Regarding your question, have you tried to initialize the slideshow or slideset again after you added the new item via javascript? I think with reinitializing it, the items should be added correctly. 

Thanks for your understanding,
Your UIkit Team
