### ISSUE TITLE
UIKit 3: issue with uk-grid-match and uk-text-[ALIGN]

### ISSUE THREAD

**Issue by gsouf** [uikit/uikit#2213]
When using ``uk-grid-match`` the text alignment fails for direct children of the flex container. 
You need to add the css rule ``justiffy-content: ...`` to get it working correctly.

See the fiddle https://jsfiddle.net/mxLka6ve/2/ that includes a ``.patched`` class that shows how I worked arround the issue

The reason is that direct children of uk-match are also flex containers:

```.uk-grid-match>*```

**Comment by florianletsch** [comment]
I am not sure this is actually an issue. 

Since... always, the direct children of the grid container have had some styles assigned to them. It is usually required to nest elements inside the grid columns. Look for example at the grid examples from the official docs, such as https://getuikit.com/docs/grid#match-height

```html
<div class="uk-grid-match uk-child-width-expand@s uk-text-center" uk-grid>
    <div>
        <div class="uk-card uk-card-default uk-card-body">Item</div>
     </div>
    <div>
        <div class="uk-card uk-card-default uk-card-body">Item<br>...</div>
    </div>
    <div>
        <div class="uk-card uk-card-default uk-card-body">Item<br>...<br>...</div>
    </div>
</div>
```

As you mention, having such a nested markup works (which is also why the `uk-text-center` works in above example.

I think we therefore won't need to overwrite the text align for these cases, as using such markup already solves the issue.
