### ISSUE TITLE
Line height for buttons

### ISSUE THREAD

**Issue by fuzenco** [uikit/uikit#2230]
Unfortunately, button text that wraps to 2 lines when in mobile portrait orientation has excessive spacing. If the line height is decreased, the button collapses on itself. It's like line height is playing too much a roll in the padding of the button.

**Comment by saschadube** [comment]
Can't see it. Please provide an example where we can inspect the issue, [like this one](http://codepen.io/anon/pen/wgzGxY)

**Comment by Lx** [comment]
This issue is evident whenever the button text wraps, and is not exclusive to mobile.  The red shaded area in the attached screenshot shows excessive line spacing between the two lines of the button's text.

![image](https://user-images.githubusercontent.com/160164/93408874-f6797200-f8d8-11ea-956b-a1a7ad1eb0aa.png)

It seems that line height is used to determine the height of the overall button when only one line is displayed, without considering cases where multiple lines may be displayed.  Perhaps a lower line height plus padding can be used for the same effect.

**Comment by Lx** [comment]
An example where the issue can be inspected, as requested:
https://codepen.io/LxAU/pen/WNwgwjP

**Comment by Lx** [comment]
@florianletsch @fuzenco please re-open, now that an example is provided as requested.

**Comment by fuzenco** [comment]
> @florianletsch @fuzenco please re-open, now that an example is provided as requested.

Thanks for keeping this alive. I’d missed the notification months ago.

**Comment by heyfellows** [comment]
Hi @saschadube , this issue is still there after almost 10 years. 
Can you please fix it or provide a workaround?
