### ISSUE TITLE
How to use with npm and webpack

### ISSUE THREAD

**Issue by mjbates7** [uikit/uikit#2244]
Hi,

Are there any examples of how to use this with NPM? All the documentation says is to do `npm install uikit` but not on how to actually use it/include additional components such as `notification`.

When I try the following code in my main `index.js` file:

`import 'uikit';`

I get the following error:

`Module not found: Error: Can't resolve 'uikit'`

Has anyone used uikit with webpack/webpack2?

**Comment by lukefisher10** [comment]
Once you have done NPM install, follow it with an NPM compile, you will see the files being created ready for use in a dist folder.

You will see a core file, and a file which contains the additional components, at which point they will be ready for you to import import uikit from 'uikit/dist/js/uikit-core.min';

**Comment by mjbates7** [comment]
I have got as far as importing uikit fine, but can't use additional components as it complains that `UIkit` is not defined:

> Uncaught ReferenceError: UIkit is not defined
    at uikit.js:5108
    at $ (uikit.js:5080)
    at Object.<anonymous> (uikit.js:5083)
    at __webpack_require__ (bootstrap 6fa2699…:555)
    at fn (bootstrap 6fa2699…:86)
    at i (notification.min.js:3)
    at Object.<anonymous> (notification.min.js:3)
    at __webpack_require__ (bootstrap 6fa2699…:555)
    at fn (bootstrap 6fa2699…:86)
    at Object.<anonymous> (index.js:8)

See picture below:

![image](https://cloud.githubusercontent.com/assets/4522738/22692495/480a6ab8-ed37-11e6-8076-c04c63135a18.png)

**Comment by PCDotFan** [comment]
Same Problem.

**Comment by dbonner1987** [comment]
I have been experiencing this issue as well. Simply including UIkit in a script tag isn't a solution for us as jQuery is included our webpack bundle.

Has anyone else came across this issue?

**Comment by jlauemoeller** [comment]
I see this as well. My conclusion is that **at the moment UIkit 3-beta-11 and earlier is not compatible with `import` use in a webpack managed app.** You have to import UIkit js and css using old-style script and link tags.

Here's what I have seen so far:

The reason the import of optional components such as Tooltip fails is that these make references to a global UIkit object. This won't be available in the host application when managed by webpack. It's interesting to note that the built-in components are actually "imported" in a way that explicitly provides them with a UIkit reference and that is the reason they work. Importing `uikit-core.js` works because that file does not contain the optional components -- `uikit.js` is really just `uikit-core.js` with the optional component source files appended verbatim.

Adding `import UIkit from 'uikit'` to the start each optional component source file partly fixes the issue; the basic `import uikit from 'uikit'` in your application code will now work (after a `npm run compile` step, of course). 

However, the problem then simply moves to the UIkit mixins (as reported by @mjbates7), which suffers from the same issue; they appear to webpack as ordinary modules and references `UIkit`, but does not import it. This is the reason we see errors in the console even when just importing `uikit-core` and not using any optional components. In this case, however, importing UIkit directly in the mixin won't help as the mixin themselves are imported by the rest of UIkit; webpack detects this circularity during `npm run compile` and marks UIkit as an external reference. This allows the `npm run compile` step to complete with the added import statements, but doesn't actually help at runtime as there will be no global external UIkit reference available when the host app is managed by webpack. 

I have tried using the weboack ProvidePlugin but didn't arrive at a configuration that worked.

**Comment by dbonner1987** [comment]
@jlauemoeller seconded.

The best solution I found so far was to `run compile`and copy it over to my app directory then require `uikit-core`. A bit of a roundabout fuss and sort of counter intuitive.

**Comment by florianletsch** [comment]
This should all work now with the current release. We have also added a basic tutorial to the docs: https://getuikit.com/docs/webpack

**Comment by cemfirat** [comment]
I try to use uikit with webpack. The self-designed svg icons are not imported.
custom icon does not load in webpack:
Issue [https://github.com/uikit/uikit/issues/3073](https://github.com/uikit/uikit/issues/3073)

**Comment by kelsh** [comment]
I  have the same problem, import uikit doesn't work.

**Comment by ruchern** [comment]
@kelsh So you're just importing the Javascript and not the stylesheets? Okay

**Comment by kelsh** [comment]
I'm doing exactly as the documentation says: 
import UIkit from 'uikit';
console.log(UIkit) //undefined

I played around with it for over an hour trying different aliasing and whatnot.  Its pretty frustrating when something as basic as import A from A doesn't work.

**Comment by wilkesreid** [comment]
It's working for me. I did `npm install uikit`, and then in my modules (I'm using VueJS single-file components) I call `import UIkit from 'uikit'` and then I can call things like `UIkit.notification(...)` and it works great.

**Comment by occult** [comment]
I got it working by using `npm install uikit` then putting the following code in index.js file. 

```
import css from 'uikit/dist/css/uikit.css';
import Icons from 'uikit/dist/js/uikit-icons';
import UIkit from 'uikit/dist/js/uikit.js'

// loads the Icon plugin
UIkit.use(Icons);

// components can be called from the imported UIkit reference
UIkit.notification('Hello world.');
```

**Comment by paulidealiste** [comment]
Besides being the best UI library this little issue still bugs it ... namely while it is true that when using the recommended way: 

```
import UIkit from 'uikit';
import Icons from 'uikit/dist/js/uikit-icons';

// loads the Icon plugin
UIkit.use(Icons);

// components can be called from the imported UIkit reference
UIkit.notification('Hello world.');
```
it does work as far as UIkit JS goes...as @occult have said...but alas icons do not get rendered and can't be seen anywhere.

I have installed it via yarn and it's uikit 3.0.0-beta.40. When I inspect my webpack bundle (sources) it clearly is present along with the uikit.js in it. Also, when i check what is imported and follow through the debugger, the icon object is present and looks all set. Finally, when I just set them through CDN links in my index.html they display ok, so it's strange.

Maybe there is something webpack related preventing umd module with icons from firing the icon functions?

**Comment by bg-wilkesreid** [comment]
@paulidealiste I would not be surprised if it's necessary for the UIkit css to also be included in the page for the icons to work.

**Comment by mjbates7** [comment]
This should be reopened in fairness @florianletsch

When I last tried it, I had the css loaded also from my bundle on the page for the layout/components etc so everything was there. 

It's an odd one..

**Comment by paulidealiste** [comment]
Unfortunately, though I missed to mention I have tried all possible css imports, directly from links in html head (from node modules and cdn), as well as through my scss setup. While all styles are there in the complete app icons are not. 
Also in my source (https://github.com/paulidealiste/GeometricShank) i'm using Electron for this, so maybe that has something to do with it, since it overrides some global variables.

**Comment by dasdeck** [comment]
Hey there!
I tried to get to the bottom of this issue.
There was a known bug that prevented webpack builds from running properly (circular dependencies and initialisation order), it has been addressed though.

Maybe I'm missing the point of this thread, but here are a few examples on how to bundle UIkit (with and without css & with icons). 

Note, the css is not needed in order for the icons to works (as seen in the examples).

https://github.com/dasdeck/uikit-example

Cheers!

JM

**Comment by paulidealiste** [comment]
@dasdeck Hey thank you so mush for the ui-kit example repo, since I have managed to find out what was the problem with my setup by looking at your example webpack configs. I have managed to include UIkit in the vendor bundle: 

`entry: {
    app: './src/index.js',
    vendor: ['uikit']
 }` 

and it seems it cound't find Icons. When I removed it from there all of your patterns for import worked.

**Comment by sburina** [comment]
Hi, guys!
The solution that worked for me - added one more line at the bottom:
```
import UIkit from 'uikit';
import Icons from 'uikit/dist/js/uikit-icons';
UIkit.use(Icons);
// The following line makes it finally work:
window.UIkit = UIkit;
```
I hope this will be helpful to someone. :)

**Comment by eirinimark** [comment]
@sburina was quite helpful! Thank you! It worked for me!

**Comment by rangka-kacang** [comment]
How come there is no participation from the core contributors regarding this issue? I'm developing electronjs + vauikitjs and come across this webpack problem.

**Comment by janschoenherr** [comment]
I don't think it's necessary to make UIkit available through the `window`. I will close this issue for now. Please comment if the issue persists.
