### ISSUE TITLE
bug modal scroll

### ISSUE THREAD

**Issue by kirich1368** [uikit/uikit#2264]
bug modal scroll
[video](https://vk.com/video_ext.php?oid=193829540&id=456239035&hash=e072ed4293f255bc)

**Comment by svjansen** [comment]
Thats because of the event.target.
If the scrollbar is clicked (mouse not hold down long enough) the **`click(e) function`** in **`mixin/modal.js`** is called.
The target of the event is the **`parent of the uk-modal-dialog`** which causes the **`isWithin(element, selector) function`** in **`util\dom.js`** to return false (which is correct because the scrollbar is no child of the dialog).

That means that
```
if (active && active.bgClose && !e.isDefaultPrevented() && !isWithin(e.target, active.panel)) {
            active.hide();
}
```
is true which hides the modal.

If thats not what's expected, a fix could be to work with coordinates and check if the mouseX is outside of the window dom e.g.

```
if($(window).innerWidth() <= event.clientX)
 // dont hide, -> mouse on scrollbar
```

**Comment by kirich1368** [comment]
thanks
