### ISSUE TITLE
tripadvisor icon in UIKIT3

### ISSUE THREAD

**Issue by Yiannistaos** [uikit/uikit#2292]
I would like the tripadvisor icon also in uikit3 as it presented here https://getuikit.com/v2/docs/icon.html

Thanks

**Comment by nblackburn** [comment]
@Yiannistaos UIKit no longer uses font awesome, it has it's own library of generic icons instead.

I can't see them expanding it out to brands to be honest.

**Comment by BobbyBabes** [comment]
Apparently you can keep using Font Awesome : https://github.com/uikit/uikit/issues/2236

**Comment by nblackburn** [comment]
@BobbyBabes Yup, the guide is here: http://fontawesome.io/get-started/

**Comment by philoest** [comment]
If you are using the src you also can create your own icon within the `src/images/symbols` folder (this has to be an svg file). And then run the command `npm run images`. After that you can use your own icon the same as the default icons. Note that the file name will be the icon name.

This will be changed in the future so that it will be easier to add custom icons and also that this will not be removed after an update, because I think this would happen now. 

And of course as @BobbyBabes already mentioned you can still use Font Awesome.
