### ISSUE TITLE
Adding params before upload

### ISSUE THREAD

**Issue by bribar** [uikit/uikit#2296]
Are we not able to add params before the upload in 3.0? before function not listed like in previous UIKit version...is there another way of achieving this?

**Comment by philoest** [comment]
Which params do you add via the before function? Doesn't it work when you create the upload component via JS `UIkit.upload(element, options)`?

**Comment by bribar** [comment]
Ya that works fine. But that is on page load, if i wanted to pass a param based on user input that would be after page load.

**Comment by philoest** [comment]
Oh, that is correct currently this is not possible the same as in UIkit2, we will add this back in a future update. 
Currently you would have to do it via the beforeAll function, but here you have to watch out since this changes the original settings of the upload. So when changing back to default you would have to reset the settings again with the beforeAll function. 
Another not so nice option currently would be initiate the upload component again, as soon as the settings have been changed.
