### ISSUE TITLE
Icon doesn't appear

### ISSUE THREAD

**Issue by mohamedsabil83** [uikit/uikit#2369]
After updating to beta9 the icons not appear unless I put the js files between `<head>` `</head>`

As following seo rules, How can I continue put the js files before the `</body>` and icons appear normally?

**Comment by jimibi** [comment]
Same thing for me

**Comment by bauer01** [comment]
see #2337

**Comment by sumanion** [comment]
I had a similar issue with beta9 when I used CloudFlare CDN. Maybe it's not your case, but for me  the problem was in the `XMLHttpRequest` to CloudFlare CDN used to load icons sprite.

The **error** was: `XMLHttpRequest cannot load https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.9/images/icons.svg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost/' is therefore not allowed access.`

The **solution** was to download icons sprite form `https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.9/images/icons.svg` to a local path `/images/icons.svg`, then to add the following CSS rule:

```css
.uk-icon::before {
    background-image: url(/images/icons.svg);
}
```

Now all icons work as expected.

I hope it will help someone.

**Comment by mohamedsabil83** [comment]
@sumanion thanx for reply but I'm not working from CDN but it's in the local project folder and didn't work for me

**Comment by janschoenherr** [comment]
Resolved with Beta 13. The icons system has been updated. Please check https://getuikit.com/docs/icons
