### ISSUE TITLE
uk-width-4-6 does not work but uk-width-2-3 does

### ISSUE THREAD

**Issue by Roeefl** [uikit/uikit#2454]
Codepen here:
http://codepen.io/Roeefl/pen/ryagoV

Is this intended behavior ?

I don't get why 2-3 would work and 4-6 wouldn't. 
It doesn't serve better readability and even if it did, 4-6 shouldn't break.

**Comment by danny-englander** [comment]
It looks like it's missing from here: https://github.com/uikit/uikit/blob/6626e0993fefaa547342bdedcd751af48a2cef4a/src/less/components/width.less

Also missing, 2-6 and 3-6

**Comment by kadirpace** [comment]
it is the case for many classes.
I think it is just because they have an already working alternatives with the same result.

2-6 => 1-3
3-6, 5-10, 2-4 => 1-2
and so on...

A little bit confusing at the start, but i think this is not bad at all.

**Comment by philoest** [comment]
Yes since it is totally the same you just ave to use 2-3 instead of 4-6. Since there is no special need for this and would just take some extra space we thought it wouldn't be needed :)

**Comment by danny-englander** [comment]
I guess from a code perspective this might sense but from a usability perspective, I think it breaks an expected pattern laid out on https://getuikit.com/docs/width under **Usage**:

`.uk-width-1-6` to `.uk-width-5-6` _The element takes up sixths of its parent container._

So for example, I am designing a theme using UIKit 3 and I want to document the grid. There's now different exceptions to an expected pattern that will inevitable break things as the OP has demonstrated in the codepen above. It also makes it much harder to document because of these exceptions. Sure, I now know that I can use 1-3 for 2-6 but doing all that maths makes certain presumptions about users where they now have to go start to convert things rather than just having an expected pattern work.

**Comment by haydnjames** [comment]
The documentation does not help. By saying '.uk-width-1-6 to .uk-width-5-6' - It does suggest 2-6, 3-6, 4-6, are acceptable classes.

**Comment by kiarashi** [comment]
I, too, noticed that uk-width-2-6 doesn't even work inside UIKit3. Is this intentional?
