### ISSUE TITLE
Table Hover Breaks At Full Screen and After in Chrome

### ISSUE THREAD

**Issue by GreenWisdom** [uikit/uikit#2459]
Using the uk-table-hover class on tables, I just noticed in Chrome, when I make the browser full screen the table rows do not highlight on hover.  They do however, highlight when clicked.  When I exit full screen (without refreshing browser) the same broken behavior continues (table rows do not highlight on hover but do when clicked).  I also tested this with Firefox and Safari, and the table hover class works just fine using those browsers; so it seems to be a Chrome issue.

The issue exists for UiKit V2 and the Beta V3, and is present when viewing the table section of the documentation in Chrome:
https://getuikit.com/v2/docs/table.html
https://getuikit.com/docs/table

Another comment - if the browser is at full screen at a refresh, then the hover works in Chrome.  So more specifically, this occurs when the browsers is not at full screen when the page is initially visited and then expanded to full screen.

**Comment by florianletsch** [comment]
Hm, this is curious. However, I think this is not related to UIkit, it seems to be a general behavior. Look at this isolated example. It also happens when I use Chrome in fullscreen there: https://codepen.io/anon/pen/evpdWG

This appears to be a known, but unfixed Chrome bug. https://bugs.chromium.org/p/chromium/issues/detail?id=170058

I don't think there's anything we can do about it.

**Comment by GreenWisdom** [comment]
That codepen is not working in the slightest.  But to confirm, did you see my comment about how the issue does not exist if the browser window is at full screen from the beginning?  And that it only exists when the browser is made full screen after visiting the page in a browser window not at full screen?  I don't think this issue should be closed.

**Comment by GreenWisdom** [comment]
Thank for looking into this though.

**Comment by florianletsch** [comment]
Okay. Do you have more ideas what this could be related to, then?

The hover style contains nothing fancy: https://github.com/uikit/uikit/blob/develop/src/less/components/table.less#L155


> That codepen is not working in the slightest.

What do you mean? In my case, I observe issues when in Chrome fullscreen, but not with other browsers.

> But to confirm, did you see my comment about how the issue does not exist if the browser window is at full screen from the beginning? 

Yes. I am guessing that this could be related to a window resize event that the UIkit JS might trigger and that might change the behavior, when the browser is already in fullscreen.

I still think it is because of the documented Chrome bug. 

Could you elaborate why you do not think it is related to that bug?

Thanks!

**Comment by GreenWisdom** [comment]
I agree with you that its a chrome bug.  I meant to follow up with another comment saying so but forgot; my apologies.  Btw..did you get my email?
