### ISSUE TITLE
Custom icons don't overwrite standard icons

### ISSUE THREAD

**Issue by gensmann** [uikit/uikit#2500]
When adding an icon called "plus.svg" in either custom/icons or custom/mytheme/icons it doesn't overwrite the standard "plus.svg" in the final .js output file (the svg string in the output .js file).

Icons with diff. names than the standard does get added correctly, but standard icons aren't overwritten.

**Comment by haydnjames** [comment]
I think the SVGs in that folder are for reference only. They appear to be hardcoded in the CSS as data URLs rather the pointed to in the traditional url('.../images/plus.svg') way.

**Comment by gensmann** [comment]
@haydnjames According to the documentation this should be possible during the build process :-)

https://getuikit.com/docs/custom-icons

**Comment by haydnjames** [comment]
You're right! Sorry. The setup for icons changed with the latest beta and I hadn't realised :)

**Comment by imarkdesigns** [comment]
yeah, these icons are getting more complicated than usual font-awesome version. though, i like the new icons... regarding icons, when checking the `uikit-icon` js file, all scripts written there are mostly svg's XML... I haven't get a chance to play around this but, I am assuming that perhaps I can add another line of svg's XML script there and see if the icons will work. as i understand, svg icons inside the folder are no longer called since it was completely rendered at js... it was very tricky at first place.

**Comment by haydnjames** [comment]
@imarkdesigns The way I understand it is that you simply drop your SVG in the icons folder then run the compiler. The icon will automatically be added to the main icons.js file ready to use in your projects. So in theory, you don't have to edit the JS file manually at all :)

**Comment by gensmann** [comment]
@haydnjames That's correct. It just had a bug in the compiling process. It has been fixed now by @janschoenherr 's commit. I can verify et works now as intended. :-)
