### ISSUE TITLE
Offcanvas extend ' .dark' has no matches

### ISSUE THREAD

**Issue by DanielNemanic** [uikit/uikit#2545]
Hi,
after changing the `@offcanvas-bar-color-mode: dark;` value to dark, I receive the following error:
`extend ' .uk-dark' has no matches`

If I switch back to light, everything is ok.

I installed UIkit from npm and bower.

**Comment by saschadube** [comment]
Yes, that's fine. It's not an error, it's a notice/warning.

The theme has one style by default which is light or dark, right? So only the inverse style needs to be added. By default UIkit has very light backgrounds and dark text colors. This means it only needs to implement ```uk-light```(to get light text colors, for dark backgrounds).

If you set the offcanvas bar to ```dark``` Nothing gets extended because your theme has dark colors by default. So you don't need extra CSS to get dark text colors for your offcanvas bar.

**If you design a dark theme**

In dark themes you have dark backgrounds and light text colors. So the inverse component should implement ```uk-dark``` (to get dark text colors, for light backgrounds).

To do so, you have to define the needed inverse color of your theme. By default it's set to ```@inverse-global-color-mode: light;```. For a dark theme just set ```@inverse-global-color-mode: dark;```. Now the your offcanvas bar would extend the ```uk-dark``` (which makes sence if you have a white offcanvas bar in a dark theme.)

Hope this explanation helps a bit...

**Comment by DanielNemanic** [comment]
Yes that's it.

I design a white theme with a white offcanvas. 
I changed the @offcanvas-bar-background to white.

In the inverse.less file after changing `@inverse-global-color-mode: dark;` the color is dark and the error is gone.
