### ISSUE TITLE
Tooltip help please

### ISSUE THREAD

**Issue by kirich1368** [uikit/uikit#2605]
check https://worldmin.ru/test.html

check  video please [https://vk.com/video_ext.php?oid=168560504&id=456239037&hash=d598bda2b34a943e](https://vk.com/video_ext.php?oid=168560504&id=456239037&hash=d598bda2b34a943e)

**Comment by askaoru** [comment]
Hello, the issue is with your scripts and not a bug with the tooltip component.

The issue that you have is with this line `$record.attr('title',getServersPlayers(players));`
Do note that you have 2 divs defined with id of `monitoring-record` which is surely not correct.

![monitoring](https://i.gyazo.com/a99831ef355597aa60de5d11b9c5cefe.png)  

I do not really understand what you're trying to achieve or what is the intended behavior, so I cant help much.

And for things like this, it's better to ask for the community help at gitter (https://gitter.im/uikit/uikit) instead of posting it as an issue since this is not a bug. And try not to open multiple same issues since you already opened https://github.com/uikit/uikit/issues/2600 before this.

**Comment by kirich1368** [comment]
It doesn't matter there...
