### ISSUE TITLE
uk-hx responsive function

### ISSUE THREAD

**Issue by tyler-x** [uikit/uikit#2721]
for example, uk-h1 is ok for large screen, but too big on smaller screen.

If responsive element can be used with these heading classes, then I can do something like uk-h3@s uk-h2@m uk-h1@l.

**Comment by ruchern** [comment]
2nd this. I am facing similar issues too.

**Comment by zzseba78** [comment]
I did the the responsive headings feature request too some time ago, since each heading size can have different styles ( color, weigth, font ) i don´t think to change the class it´s a good idea, since you only want to change the font size according to each responsive size.

I like more the approach of carlos durán here.
https://github.com/uikit/uikit/issues/2583

**Comment by florianletsch** [comment]
This is a good idea! I have put it on the team list to discuss. 

Since this has already been suggested in #2583, I will close this issue as a duplicate.
