### ISSUE TITLE
定制工具不能正常使用，麻烦修复一下，谢谢！

### ISSUE THREAD

**Issue by renruiquan** [uikit/uikit#2730]
地址：http://www.getuikit.net/docs/customizer.html（很多JS都报http404错误。）

### UIkit version

3.0.0-beta.25

**Comment by lupuxyz** [comment]
中文网的问题，请使用官方的v2定制工具 https://getuikit.com/v2/docs/customizer.html

**Comment by florianletsch** [comment]
Please phrase your support issue in English in the future, thanks.

Google Translate helped me guess what your issue is. Please note that getuikit.net is not an official website and not hosted by us. As @lupuxyz has correctly pointed out, you can find the Customizer for UIkit 2 on the official .com website.
