### ISSUE TITLE
CSS grid?

### ISSUE THREAD

**Issue by paaljoachim** [uikit/uikit#2787]
I have been hearing a lot of good stuff about CSS grid:
https://css-tricks.com/snippets/css/complete-guide-grid/

https://wordpress.tv/speakers/morten-rand-hendriksen/

There are a lot of articles out there. It seems to be taking over for flexbox.

**Comment by saschadube** [comment]
I think it won't what you call "take over". Both fit great for different use cases. 

Building a grid with ```flex``` works great for a CSS framework because you can have all kind of modifier classes like different widths, etc. At first sight, a useful implementation of ```grid``` into a CSS frameworks looks harder. We have to think more about what would be the best implementation.

In the meantime lets see what other CSS frameworks come up with regarding ```grid```.

But one thing for sure, it won't replace the current grid build with ```flex```.

**Comment by paaljoachim** [comment]
Thanks for the response Sascha!

Btw
I am using the Beans WP framework that incorporates UIkit. The more I get into it the more interesting Uikit looks.
