### ISSUE TITLE
Sticky component placeholder doesn't update dimensions on resize

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#2834]
### UIkit version

3.0.0-beta.28

### Reproduction Link

https://codepen.io/anon/pen/MvpqeX

### Steps to reproduce

Open reproduction link.
Change window width from large to small size so that the text inside the sticky compontent will wrap.

### What is Expected?

Sticky placeholder updates it's height accordingly to the height of the associated sticky element.

### What is actually happening?

Sticky placeholder doesn't update it's height.

### Example case

Let's say you have a page header like the one on the UIKit documentation website.
The header should shrink to a lower height on small (mobile) screens (e.g. from 80px to 60px height).
Due to the fact that the height of the placeholder doesn't change, the vertical distance to the main content container doesn't update accordingly.

**Comment by wolfcreative** [comment]
I agree. Found the same error in his project

**Comment by bsdahl** [comment]
I am having the same issue when combining a sticky navbar with the visibility component. Below the medium breakpoint my navbar is hidden, and when resizing above the breakpoint, the sticky navbar is visible again, but the placeholder height is stuck at 0, causing content below the navbar to be partially covered by the navbar.

**Comment by bsdahl** [comment]
I was able to solve the issue by modifying the core/sticky.js line 132. I'm not sure if this is the optimal solution. But it seems to me that the write function should not read the placeholder height because when the placeholder is set to display: none, then its offsetHeight will be forever set to 0.

`                        outerHeight = (this.isActive ? placeholder : this.$el).offsetHeight, el;`
to
`                        outerHeight = this.$el.offsetHeight, el;`

https://github.com/uikit/uikit/blob/40e0572aa0e2ce654378c21c59a1115d5fb435c3/src/js/core/sticky.js#L132
