### ISSUE TITLE
child-width not consistent

### ISSUE THREAD

**Issue by flyboarder** [uikit/uikit#2857]
`uk-child-width-1-1` does not exist, however `uk-child-width-1-1@s` - `uk-child-width-1-1@xl` do exist, these are not documented.

**Comment by saschadube** [comment]
Mmmh, `uk-child-width-1-1` does not exit because that's the default grid behavior. There is no need for this class when using the grid. That's why it is left out in the docs [here](https://getuikit.com/docs/width#equal-child-widths).

`uk-child-width-1-1@s` to `@xl` exist and are needed. In the docs for [Responsive Width](https://getuikit.com/docs/width#responsive-width) the actual width is left out, e.g. `uk-child-width-*@s`.

So, what do you suggest to improve the docs?

**Comment by flyboarder** [comment]
Perhaps mention it as the default behavior so that we know it's available for responsive widths.

**Comment by zzseba78** [comment]
You can create a PR in the UIkit docs to make this point clear. 
Please close this issue. 👍
