### ISSUE TITLE
Is UIKit still in development or is it dead?

### ISSUE THREAD

**Issue by MyouTo** [uikit/uikit#2905]
Hey there,

I was not sure where to ask, so I came here. Sorry, if this is the wrong place.

I am planning on a new project and was looking for a framework. I did work with UIKit a while ago, so I thought I give it another try. 

I checked out the website and saw, that version 3 is in beta, but there seem to be missing many components in it. 

What worries me the most is that there seem to be not much development going on or it is rather slow. 
Last update was over 1 ½ months ago and even before there was not happening that much. At least the progress seem to be extremely slow, form what I can tell.

Anyway, my question is - should I really use UIKit or is it dead? As far as I can tell, they are nearly a year in beta now and far away from being finished. Please correct me, if I am wrong!

I did check on the people behind UIKIt and it looks like, that they started a few things, but did not finish them or at least do not support them much. Their CMS Pagekit seems to be dead as well. Maybe I am just missing something here. Does not want to offend anyone!

The reason I am asking is, that I read many good things about UIKit, but I am not sure, if it is a good idea to start a new project, if you cannot be sure, that the framework you are using will ever be finished or supported in a year or so.

Again – Maybe I missed something here, so please correct me or let me know if there is any source, where I can get more insights.

Thanks for your help!

**Comment by zzseba78** [comment]
First of all I clarify that I am not part of the development team of UIkit, I am just another user, with this in clear here are my first thoughts.

1. As you will know if you check on the people behind UIKIt, Yootheme is a company dedicated to themes market, and UIkit is a core part of your business, having this in mind I doubt that they abandon a project that is a key part of your their business.

2. I like to think UIkit 3 is a new product, and I do not see it as "incomplete" for not having components present in version 2 ( and in fact v3 have more components that v2 😄  ), I see it as a new product better to its previous version and expanding . Surely in the course of time will add components and functionalities (in fact there are several ongoing, such as the new lightbox, slideshow, remove JQuery dependency). So... a lot of work for a dead project!

3. Perhaps the speed of development of UIkit was diminished this last month, perhaps by vacations (they are human after all). But the pace of work on UIkit is almost daily, and you can corroborate it in Github.I don´t know many free frameworks that work with this level of intensity, and you?

4. UIkit is mature and has been around for years.

5. The last commit was yesterday 😄 

So, what do you think? 
I think that you should check thing a little more in depth.

Good luck!

**Comment by stebeg** [comment]
Hi,

my recommandation would be to use another ui framework. 
I used Uikit v2 in a large project and it did it's job. It still has some minor bugs and I don't expect them to be fixed, especially because all v2-issues were closed unresolved on v3 beta release. So I don't see v3 as a new project. It's just a new release of v2 with more bugs and less useful features.

There are some very good alternatives to uikit. Bootstrap and Foundation are just 2 of them. Both are stable, well documented and feature-rich.
Fundation: https://foundation.zurb.com
Bootstrap: http://getbootstrap.com

Just my 2 cents.

**Comment by saschadube** [comment]
UIkit is far from dead. I'm a little shocked you got this impression.

We use UIkit 3 in production a year now and it is really stable. It's just labeled beta because some components from UIkit 2 are missing. We will call it officially stable when the slideshow and dynamic grid components are ready.

We are currently working on the [slideshow](https://github.com/uikit/uikit/tree/feature/slideshow) and on removing the jQuery dependency.

**Comment by krosoftware** [comment]
I hope that existing code of Ulkit 3 will work when you remove jQuery dependency?

**Comment by steven-ferrer** [comment]
@krosoftware, have you checked [UIKit](https://www.npmjs.com/package/uikit) from npmjs.com? based on that site, it has 0 dependency.
