### ISSUE TITLE
adding fill option for icons

### ISSUE THREAD

**Issue by samanmohamadi** [uikit/uikit#3000]
I think it would be very useful if icons can be filled with custom color.

**Comment by aarongerig** [comment]
Simply apply a `color: value;` with css and the icons will adapt to it.

**Comment by janschoenherr** [comment]
Can this be considered resolved?

**Comment by samanmohamadi** [comment]
I think the way @aarongerig  suggested will affect stroke color not fill color.

**Comment by aarongerig** [comment]
@samanmohamadi SVG icons with the class `uk-icon` inherit the color for `fill` and `stroke` color, as you can see here: https://github.com/uikit/uikit/blob/54b0f37db96b1e29bf43edc9db180a6bc7dfa9eb/src/less/components/icon.less#L91-L99

You wanted to fill out the default UIkit icons, which is not possible, because the don't have a "filling" in the first place. If you want to achieve that, you will have to create custom icons, as described here: https://getuikit.com/docs/custom-icons

**Comment by samanmohamadi** [comment]
tnx

**Comment by Dragonchasers** [comment]
For the icon:star for example, if you inspect a page it does have a fill, set to none. 

Adding a color to the css colors the stroke but not the fill. 

<polygon fill="none" stroke="#000" stroke-width="1.01" points="10 2 12.63 7.27 18.5 8.12 14.25 12.22 15.25 18 10 15.27 4.75 18 5.75 12.22 1.5 8.12 7.37 7.27"></polygon>
