### ISSUE TITLE
Modal and Tooltip are not working with SCOPE mode

### ISSUE THREAD

**Issue by Yiannistaos** [uikit/uikit#3057]
### UIkit version
3.0.0-beta.35

### Browser
Google Chrome
Version 62.0.3202.94 (Official Build) (64-bit)

### Reproduction Link
https://jsfiddle.net/Yiannistaos/wmvn6djb/1/

### Steps to reproduce
Clean UIKit installation with UIkit scope mode https://getuikit.com/docs/avoiding-conflicts#scope-mode

### What is Expected?
Modal and Tooltip components should work in scope mode.

### What is actually happening?
I'm trying to use Modal and Tooltip with scope mode.
I had the version 3.0.0-beta.24 and I've tried to update into the latest UIkit version 3.0.0-beta.35.
It worked with version 3.0.0-beta.24, but is not working with version 3.0.0-beta.35.

### DEMO on jsfiddle.net
https://jsfiddle.net/Yiannistaos/wmvn6djb/1/

**Comment by dasdeck** [comment]
Hey! Thanks for the report!
Turns out the documentation has not been updated properly (which will come next).

in your fiddle, simple add:
```javascript
UIkit.container = UIkit.util.$('.uk-scope');
```
to your javscript

..doc..
Now you need to tell modals, tooltips and the likes where to append themselves into the dom when they want to show. To do so, set the following parameter to UIkit:

//simply pass the selector
UIkit.container = '.uk-scope' 
...
//or you can set an element directly, for example
UIkit.container = document.getElementById('#id-of-scope-element-or-element-inside-your-scope');

Cheers!

**Comment by Yiannistaos** [comment]
Thanks, @dasdeck.

It works now!

Here is the correct version https://jsfiddle.net/Yiannistaos/wmvn6djb/2/
