### ISSUE TITLE
Modal dialogs are not removed from the DOM when closed

### ISSUE THREAD

**Issue by ChrisLandowski** [uikit/uikit#3121]
### UIkit version
3.0.0-beta.35

### Browser
All

### Reproduction Link
https://getuikit.com/docs/modal

### Steps to reproduce
Click any of the Dialog, Alert, Confirm or Prompt buttons to open a modal dialog and then close it.

### What is Expected?
The div.uk-modal element and it's children should be removed from the DOM.

### What is actually happening?
The div.uk-modal element and it's children still exist in the DOM.
Clicking the same button again, adds another div.uk-modal to the DOM.

**Comment by sargac** [comment]
As of Feb 16 2020, the issue is still present -- maybe fixed then, but in the last UIkit 3 version, I can confirm the **UIkit.modal.alert()** call creates multiple DOM nodes. After closing the modal window, the element stays in the DOM. The next call then creates a new node, and so on -- as one can see on the image below: 

![image](https://user-images.githubusercontent.com/20192194/74612185-5883b600-5103-11ea-8fe7-cc74b7193663.png)

I tried to destroy it by using the following code:

```
UIkit.util.on(document, 'hidden', '.uk-modal', function() {
	UIkit.modal('.uk-modal').$destroy(true);
});
```

But then another instance doesn't work -- it just gets created in the DOM, grayed out -- similar to the past items from the image above.

It would be nice, if the elements are destroyed automatically, after closing them. Currently, I am removing the instance using the `$('.uk-modal').remove();` fix.

**Comment by sargac** [comment]
Thank you for the fix -- the element is now promptly removed -- but I've just discovered another variant of the issue, as seen on the example below.

For instance, when using **hide** event (I haven't tried the other ones), the initial call gets repeated, as one can see on the image below. With each click, eg. modal window display, the on hide event code repeats its execution, each time by one time more -- as if something is not cleared on modal removal. So, when I click and show the modal window 5th time, I get the code, executed 5 times (with old values, as well).

Any help would be appreciated.

```
UIkit.modal.alert(data.message, {
	labels: {
		ok: _('ok')
	},
	escClose: true,
	bgClose: true
});
UIkit.util.on(document, 'hide', '.uk-modal', function() {
	console.log('msg ...');
});
```

![image](https://user-images.githubusercontent.com/20192194/75118873-4f07ca00-567e-11ea-8316-72062a45c14e.png)

**Comment by janschoenherr** [comment]
@sargac If you manually register an event handler on the document, you'll have to remove it too. You could also use `UIkit.util.once`.

**Comment by sargac** [comment]
@janschoenherr Thank you very much! Now it's so obvious :) ... I thought the event handler is gone with the element ... oh well.

**Comment by directcuteo** [comment]
Hi! Is this issue really fixed? For me it's not working, the modal element is not removed from the DOM.
I can see the same wrong behaviour on Uikit's docs page too.

https://getuikit.com/docs/modal

**Comment by janschoenherr** [comment]
@directcuteo Yes, the dialogs are removed: https://getuikit.com/docs/modal#modal-dialogs

If you open a modal that's already located in the DOM, it is only moved to the container. It is not removed on close.

**Comment by chidimo** [comment]
This still happens. The DOM node is not removed. I'm using UI Kit v3.5.7

**Comment by ktj** [comment]
Had the same problem.
https://stackoverflow.com/questions/60871974/uikit-modal-element-is-not-removed-from-dom-when-parent-component-is-destroyed
This solved my problem. 
Use the container attribute
https://getuikit.com/docs/modal#modal-dialogs
