### ISSUE TITLE
Just defining uk-scrollspy with no options doesn't work

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3165]
### UIkit version

3.0.0-beta.38

### Browser
Chrome

### Steps to reproduce
1. Create an element with uk-scrollspy but no options
2. The default class "uk-scrollspy-inview" isn't added when in view and inview isn't triggered. 

### What is Expected?
The uk-scrollspy-inview class should be added and inview should be triggered. 

### What is actually happening?
Nothing is happening unless you define cls: which isn't great if you are using uk-scrollspy to action JavaScript on inview trigger, for example a GSAP animation.

**Comment by TomS-** [comment]
One thing I've noticed is the scrollspy items get an empty style tag? I'm not entirely sure why.

**Comment by janschoenherr** [comment]
Does the above commit resolve your issue?

**Comment by sabinaHH** [comment]
Dear Team,

I am experiencing the same issue but only on iPhones and only when uk-scrollspy is assigned to an `<svg>` tag. All desktop browsers (minus IE) and Android devices work fine.

CodePen: https://codepen.io/sabyx/pen/LYpjWjR
iOS version: 13.4.1
Tried on the following browsers on iPhone: Safari, Chrome, Edge, Firefox 

The "visibility: hidden" property should get removed when the element comes into view and the class "uk-scrollspy-inview" should get added, together with the relevant animation class. 

The normal flow is pictured below, but on iPhones the "visibility" property remains set to hidden. 
 
![uk-scrollspy-svg-issue-ios](https://user-images.githubusercontent.com/50639188/81050351-20993d00-8ec0-11ea-9df2-a91f21b15df5.png)

Any hints as to what I could do to avoid this issue?

Side note: Uk-scrollspy in combination with a `<div>` tag works fine on iPhones so the issue seems to occur when using uk-scrollspy within an `<svg>` tag.
