### ISSUE TITLE
Server Side Rendering 

### ISSUE THREAD

**Issue by mechanic22** [uikit/uikit#3207]
-->

### UIkit version

3.0.0-beta.39

### Browser
N/A Server Side (node.js)

### Reproduction Link
Don't have one

### Steps to reproduce
Create a react.js application with server side rendering in node.js
Attempt server side rendering.

### What is Expected?
Server would properly render (or skip) rendering of UIKit components if window is not available

### What is actually happening?
Get a server side error stating window is undefined.

NodeInvocationException: Prerendering failed because of error: ReferenceError: window is not defined

**Comment by mechanic22** [comment]
FYI it doesnt seem ideal, however I was able to get it working by removing all uk-* and data-uk-* attributes and moving the rendering to the componentDidMount() function in reactcomponents.

I also had to not import UIKit at the top but pull it in only when needed. When it was imported or at the top of the page, i would get the window error. 

```
import * as React from 'react';

export class Spinner extends React.Component<{}, {}> {

    spinner: HTMLDivElement | null;

    componentDidMount() {
        if (this.spinner) {
            var UIKit: any = require('uikit');
            UIKit.spinner(this.spinner);
        }
    }

    public render() {
        return <div ref={node => { this.spinner = node; }}></div>;
    }
};
```

**Comment by mechanic22** [comment]
Yea it appears that for some reason the DOM watching that should be occuring is not happening in a react project. I will try and get a demo app thrown together.

**Comment by sisp** [comment]
It seems I'm having the same problem when using UIkit with [GatsbyJS](https://www.gatsbyjs.org). When I use UIkit icons, e.g. `data-uk-icon='<some icon name>'`, the icon is almost never inserted - only very rarely and nondeterministically.

**Comment by platedbay** [comment]
Sorry to resurrect this from the dead, @sisp did you ever figure out how to fix this? I'm running into this as well in my GatsbyJS v2 app. The icons for me do not load when I load the page first time, but inter-page navigation works (probably due to the client-side rendering vs the initially server side rendered code).

**Comment by BayPhillips** [comment]
Sorry to resurrect this from the dead, @sisp did you ever figure out how to fix this? I'm running into this as well in my GatsbyJS v2 app. The icons for me do not load when I load the page first time, but inter-page navigation works (probably due to the client-side rendering vs the initially server side rendered code).

**Comment by dasdeck** [comment]
Hey there! SSR is not really supported for UIkit. However, I wrote a simple wrapper that will at least make UIkit boot on the server. It works with jsdom. 

https://github.com/dasdeck/uikit-ssr

You can either use this wrapper or can get some inspiration on how to solve it in your environment.

Cheers!

**Comment by chrisk8er** [comment]
hi @dasdeck , thanks for sharing this wrapper. how can I use this wrapper on gatsby?
