### ISSUE TITLE
Off-canvas close unexpectedly when click nav item in it.

### ISSUE THREAD

**Issue by RayHY** [uikit/uikit#3359]
### UIkit version

3.0.0-beta.42

### Browser
ALL 
### Reproduction Link
https://codepen.io/anon/pen/VxMpro
### Steps to reproduce
Open Off-canvas, click the `Parent - without id` and `Parent - with id`.
### What is Expected?
Off-canvas don't close when click Parent list item.
### What is actually happening?
Off-canvas close when click `Parent - with id` and `Parent - without id` do not.

I found this https://codepen.io/ezra_siton/pen/dRVpPX after searching for same issue. I just fork this and add a new `<ul>`element  to Off-canvas in line 50. and and id for `<h1>` element in line 110.
Please forgive me for my poor English.

**Comment by Jinxiapu** [comment]
In fact, I try to use UIkit 3 in my blog. I complete a [test page](http://dian.jinxiapu.cn/blog.html) (In Chinese). Off-canvas and nav work correctly in Chrome and Firefox(Yes! With id!). But in Edge or IE or some Android Browser, off-canvas close unexpectedly when click nav parent item. 
I can't thought out what happens because I know nothing about js. So I just choose a simple way to reproduce this bug(maybe).
