### ISSUE TITLE
Icons not working in React, while using data-uk-icon

### ISSUE THREAD

**Issue by dmneasis** [uikit/uikit#3361]
### UIkit version

3.0.0-beta.42

### Steps to reproduce

`import '../node_modules/uikit/dist/css/uikit.min.css';`
`import '../node_modules/uikit/dist/js/uikit.min.js';`
`import '../node_modules/uikit/dist/js/uikit-icons.min.js';`

`<span className="uk-icon uk-margin-small-right" data-uk-icon="icon: home"/>`

### What is Expected?

To see the icon.

### What is actually happening?

Icon not being shown.

**Comment by drmzio** [comment]
Seems to work fine in the latest version

Demo: https://codepen.io/drmzio/pen/gKaGvb

**Comment by dmneasis** [comment]
Solved: It works if you link both the uikit css and the js directly into the static index.html. It doesn't if your import them inside the React Component.

**Comment by JesusTheHun** [comment]
This problem is still present with the latest version to date, 3.0.0-rc.22.

The expectation is to be able to inject the javascript through react, like any other npm javascript lib.
Right now we have to copy the source into the public directory, and link it directly into the `index.html`. This feel unnatural.

This prevent updates from npm and therefore the benefits of bug fixes and security updates.

Please re-open this issue and give it a fix.

**Comment by Sadkit** [comment]
Given the 494 open issues that can I see at this time and given that I am not a "UIKit developer", I think this is not a major problem.

Possible solutions to the npm updates, without touching UIKit code:

- Include scripts via CDN in `index.html,` setting up a redirect that always goes for the latest version

- Create a uikit subfolder in `public` -> `npm init` in the subfolder -> `npm install --save uikit` -> correctly link UIKit locally in the `index.html` -> write script in package .json to automate

Example script:
`"scripts": {
    "my-install": "npm install && npm install --prefix public/uikit"
  },`

Then run `npm run my-install` instead of `npm install`

**Comment by erichonkanen** [comment]
running into similar issue in an ember.js project when rendering a shadow dom component... I resorted to manually loading the css/js from our public assets folder thinking that would solve the problem, but still the icons don't render :/ any ideas?
```
{{#-in-element this.shadow}}
  <link rel="stylesheet" href="assets/lift-experience-builder.css">
  <link rel="stylesheet" href="assets/css/aqkit.min.css">
  <script src="assets/js/aqkit.min.js"></script>
  <script src="assets/js/aqkit-icons.min.js"></script>

  <span uk-icon="icon: lift-targeted; ratio: 0.8"></span>

  {{yield}}
```
