### ISSUE TITLE
Yarn watch

### ISSUE THREAD

**Issue by Vovchan079** [uikit/uikit#3424]
I do not have the yarn watch command. The process is started, but if you make changes to the Less files, the CSS files are not compiled automatically. Each time you have to manually enter the command "yarn compile"

**Comment by dasdeck** [comment]
I'm not sure I understand you correctly.
`yarn watch` seems to work just fine over here.
Are you talking about your own custom less?
Only less files inside the UIkit directory are watched.

Cheers!

JM

**Comment by Vovchan079** [comment]
I edit the original files that are in node_modules / uikit / src / less / components / .less. Yarn watch does not work for me. The terminal is in the standby mode, I make changes to the original LESS files, but the compilation does not happen. At the same time yarn compile works well.

**Comment by dasdeck** [comment]
Ok, I'm happy to look into it, you'll have to provide me some repo/steps/info to reproduce the issue though. Out of the box, everything works just fine.

**Comment by Vovchan079** [comment]
I made an archive with all the source files that I work with. Could you see it? Thank you!
https://yadi.sk/d/N2Cx_bRL3YUnw3

**Comment by dasdeck** [comment]
Ah, ok, I see now. It does not work when running inside another `node_modules` folder.
The issue seems to be related to this:
https://github.com/remy/nodemon/blob/master/faq.md#overriding-the-underlying-default-ignore-rules

As a quick workaround put a `nodemon.json` inside your uikit folder and add this as content:
```json
https://github.com/remy/nodemon/blob/master/faq.md#overriding-the-underlying-default-ignore-rules
```
We will consider this as a possible fix, if it has no bad side effects.

Cheers!

JM

**Comment by Vovchan079** [comment]
Thank you very much for the help! Now everything has worked.
