### ISSUE TITLE
Add PostCSS Autoprefixer

### ISSUE THREAD

**Issue by miljan-aleksic** [uikit/uikit#3538]
Hi, the PostCSS Autoprefixer is quite popular and convenient. I am wondering why it was not implemented yet in the build process. Some advantages:

- Smaller and cleaner source code
- Clean code for custom themes that import the base and self build.
- Target browsers list that can be adjusted as the project evolves.

**Comment by saschadube** [comment]
Please point us to some examples in the source code where this would be useful.

**Comment by miljan-aleksic** [comment]
Sure, [these lines](https://github.com/uikit/uikit/blob/develop/src/less/components/progress.less#L36-L37) for example:

```
-webkit-appearance: none;
-moz-appearance: none;

// could become
appearance: none;

// and levarage to postCSS to prefixing
-webkit-appearance: none;
-moz-appearance: none;
appearance: none;
```

You can quick test it at https://autoprefixer.github.io/

As a bonus, you could use the postcss-scopify plugin to deal with the scoped build, and create a custom plugin for the edge cases.

**Comment by saschadube** [comment]
Ok, that's 1 line of code we would save in the source and 1 line of code which is needless in the dist. For us it doesn't justify the integration of the PostCSS Autoprefixer.

Overall UIkit doesn't use many vendor prefixes and in most cases they are needed just for the specific browser. We have the vendor prefixes exactly in control and there are no needless declarations added to the dist. We also noticed over the last years that less and less vendor prefixes are needed. Firefox and Edge even support most `-webkit` vendor declaration. That's why I think vendor prefixes will continue to decline in the future.

**Comment by miljan-aleksic** [comment]
They are few more, but more than saving lines of code the autoprefixer and postCSS in general is about automating tasks and avoid issues in the long run.

Autoprefixer relies on [browserlist](https://github.com/browserslist/browserslist) to target the right browsers. Updating those settings is all what it takes to fine tune the prefixes now and in the future. 

They may decline or they may arise, we don't know that and relying on a tool to take careof that seems the best option.

Anyway, thanks for considering.
