### ISSUE TITLE
Allow sticky component for table head

### ISSUE THREAD

**Issue by emanueljacob** [uikit/uikit#3588]
### UIkit version

3.0.0-rc.16

### Browser
Latest Safari/ Latest Chrome/Latest Firefox
### Reproduction Link

Test 1 - default
https://codepen.io/jannisr/pen/OoeEjd

Test 2  - workaround
https://codepen.io/jannisr/pen/rZEvOP

### Steps to reproduce
Use a desktop device.
See codepen 1 and workaround test in codepen 2. 
Scroll a bit down to see whats happening.

### What is Expected?
Apply the sticky component to a responsive uikit table head, in order to show the heading as long as the table is in viewport.

### What is actually happening?
the table head shrinks and is not displayed correctly, because the table thead th elements do not know the corresponding table tbody th's width, on which they depend on. 
I tried to use a workaround by applying a uk-sticky attribute in each table thead th element and then use the sticky components option "width-element" in order to get the width of the corresponding tbody elements. this also does not work.

**Comment by hurradieweltgehtunter** [comment]
Any news on this? I ran into the same issue :(

**Comment by hurradieweltgehtunter** [comment]
So I ended up creating two separate tables:
### Table 1
```
<table uk-sticky="bottom: #table2; offset: 80; top: 15" style="z-index: 981; background: white;" class="uk-visible@s uk-table uk-table-hover uk-table-divider uk-table-top uk-text-center uk-table-middle uk-margin-remove">
```
which holds **only** the `<thead>` part. Note the `uk-visible@s` in here, see below why this is needed.

### Table 2
```
<table id="table2" class="uk-table uk-table-hover uk-table-divider uk-table-top uk-text-center uk-table-middle uk-margin-remove">
```
which holds also the `<thead>` part but slightly modified (Note the `uk-hidden@s`, see below why this is needed):
`<thead class="uk-hidden@s">`

This table contains the actual data rows and columns.

### All together it looks like:
```
<div class="uk-overflow-auto">
  <table uk-sticky="bottom: #table2; offset: 80; top: 15" style="z-index: 981;" class="uk-visible@s uk-table uk-margin-remove">
    <thead>
      <tr>
        <th class="uk-width-1-2">foo</th>
        <th class="uk-width-1-2">bar</th>
      </tr>
    </thead>
  </table>

  <table id="table2" class="uk-table uk-margin-remove">
    <thead class="uk-hidden@s">
      <tr>
        <td class="uk-width-1-2">foo</td>
        <td class="uk-width-1-2">bar</td>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td class="uk-width-1-2">blu</td>
        <td class="uk-width-1-2">blu</td>
      </tr>
    </tbody>
  </table>
</div>
```

### Some notes
- the wrapping `<div class="uk-overflow-auto">` is for a responsive table (see [https://getuikit.com/docs/table](https://getuikit.com/docs/table))
- the classes `uk-visible@s` and `uk-hidden@s` on the `<thead>` elements are needed because on small devices the sticky `thead ` breaks when the responsive table layout kicks in. The workaround is to not have a sticky header on small devices.
- I added `uk-margin-remove` on the `<table>` elements to remove the margin between the two tables so it looks like one.
- All columns (`th` and `td`) need the `uk-width-*` classes to set the same with across the table borders. This also means that i does not work with auto width classes (`uk-width-expand` etc.)

I know this is a little hacky and has some drawbacks. Also i'm not sure if and how this will affect HTML validation or even SEO. Technically it is not 100% correct HTML code. In my case it is in a gated environment so SEO is not affected.

But until there's no solution out of the box it works for my purposes and maybe it helps someone out there too.

Have a good one.

**Comment by arminghm** [comment]
It is open since 2018, any update on this? can we use [Sticky](https://getuikit.com/docs/sticky) to achieve table sticky header?!

**Comment by janschoenherr** [comment]
I think it would be easiest to use `style="position: sticky; top:0;"` instead of the Sticky component.

**Comment by arminghm** [comment]
Indeed we can dig into it and fix the element's position somehow, just like @hurradieweltgehtunter workaround, but it would be nice to have sticky header inside a table also by front-end framework.

**Comment by atsuya007** [comment]
you can create a class .uk-thead-sticky th{ position: sticky; top: 0; } 

next in your table use class="uk-table uk-thead-sticky" its work fine :D :D
