### ISSUE TITLE
Modal doesn't close properly if the CSS transition property is set on .uk-modal-dialog

### ISSUE THREAD

**Issue by JeremieD** [uikit/uikit#3688]
This is a really weird bug I encountered while working with modals in the latest release candidate.

### UIkit version
3.0.0-rc.25

### Reproduction Link
https://codepen.io/jeremied/pen/BvaYqR

### Explanation
As you can see in the codepen, when I style the modal dialog element with a border, and specify an transition value for that border, the modal fails to close properly and doesn't set itself to "display: none", as it should normally do. I couldn't find it in the UIkit source, but I suppose there is something that's waiting for a specific transition to happen and it fails? I didn't investigate more than that. I also haven't really tested with other CSS properties and what transition time makes it fail, my codepen should be useful for that.

**Comment by zzseba78** [comment]
With `transition: border .2s ease;` you are cancelling transform transitions and opacity on the modal dialog, and just animating the border. Not a bug. Try other way in your css.

**Comment by JeremieD** [comment]
I understand, but I do feel like it is not very practical that I can't customize the modal fully. It was also a hell to debug.

**Comment by zzseba78** [comment]
Of course you can customize it, but have in mind that the modal works in a certain way, and your problem it´s more basic css understanding that a uikit bug.

**Comment by jcaillot** [comment]
"it´s more basic css understanding that a uikit bug"
agreed

I wanted to somewhat "hack" the modal component in order to display a loading animation.
the simpified code looked like this :

```
UIkit.modal(loadingLightbox}).show();
img.src = "possibly-heavy-image.png";
img.addEventListener("load", e => {

    // doing heavy stuff with the image involving canvas etc.
    UIkit.modal(loadingLightbox).hide();
});
```

This worked on slow mobile devices, as well on desktop with **big** images. 
Using a tiny image, the screen freezes on Chrome 67 and chromium siblings (It still works tough on Safari 12). The modal is not visible anymore but stays in the DOM and blocks everything.

The behaviour is easy to reproduce then:

 ```
UIkit.modal(loadingLightbox).show();
//  while the modal slowly opens with transition
// do something fast or not so fast...
UIkit.modal(loadingLightbox).hide();
```
        
The fix was straightforward for me :

```
 UIkit.modal(loadingLightbox).show();
setTimeout(function () {
        UIkit.modal(loadingLightbox).hide();
       }, 120);
```

the issue is the this 120 is kinda arbitrary here!

**Comment by janschoenherr** [comment]
@jcaillot Is this still reproducible with the latest version? If so, please open a separate issue.
