### ISSUE TITLE
Tabs disable Switcher animations

### ISSUE THREAD

**Issue by adleviton** [uikit/uikit#3720]
Just curious why animations don't seem work when Switcher is combined with Tabs, but animations do with with other Switcher combinations?

**Comment by KadenLNelson** [comment]
I think I'm encountering your same problem on my projects, could you share your source?

**Comment by adleviton** [comment]
You can see an example here:
https://codepen.io/aleviton/pen/wRLQaW

For the time being, I used Subnav instead of Tabs, and styled the Subnav to look like Tabs.

**Comment by KadenLNelson** [comment]
Try changing `<ul uk-tab...>` => `<ul class='uk-tab'...>`

**Comment by adleviton** [comment]
That's a nice workaround. I just updated on codepen.

**Comment by directcuteo** [comment]
Hi. Do you have any idea how can you remove the animation on runtime? 

My case: I set the animation to fade `data-uk-switcher="animation: uk-animation-fade"` and then I want to remove the animation. I tried `data-uk-switcher=""` but the animation is still applying on the selectors because of Uikit's background logic because I didn't exactly replaced the current animation. 
If I start without specifing the animation, there will be no animation indeed, but that's not my case...
