### ISSUE TITLE
Uk-width-expand on IE 11

### ISSUE THREAD

**Issue by eladnova** [uikit/uikit#3785]
### UIkit version
Any 3.X but I'm using 3.0.3

### Browser
IE 11

### Reproduction Link
https://codepen.io/edenstudios/pen/qvWpGo

### Steps to reproduce
Open the Codepen in IE 11 on a large monitor.

### What is Expected?
Col-2 div should be horizontally centred as it has the properties of
- uk-width-expand
- max-width: 600
-margin:0 auto

### What is actually happening?
On largest breakpoints / very wide screens using IE11, the div floats right.

**Comment by zzseba78** [comment]
Did you try with the col-2 element in a separate div inside the column ( so you don´t mess with the column, and style the element only ( max width and centered in the column )?

**Comment by eladnova** [comment]
Figured this out. 
1. Remove my custom margin
2. UIKit has a native uk-margin-auto. Use that

**Comment by zzseba78** [comment]
But it´s the same result right?

**Comment by geckoseo** [comment]
Unfortunately it's not possible to test the pen while using IE11, but the problem is possibly related to a bug in IE11 with regards to the Flexbox model.

IE11 requires a unit to be added to the third argument, the flex-basis property, which when looking the source of the Uikit code appears to be missing.

It's also a probability that the flex-basis property needs to be vendor prefixed for IE11.

[See MFST documentation](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/hh673531%28v%3dvs.85%29#setting-the-flexibility-of-a-child-element)

**Comment by janschoenherr** [comment]
We have dropped support for IE 11.
