### ISSUE TITLE
Treeview  ??

### ISSUE THREAD

**Issue by Diaskhan** [uikit/uikit#3850]
Its possible to implement 
focsuable Treeview?

With json input data  ?

**Comment by sudoranger** [comment]
I believe you are Windows user. Treeview should just die in this century. It was invented by Microsoft back in the 90's. Nowadays, there are multiple devices with different screen sizes. Treeview is not touch friendly especially on a smaller mobile devices (due to it's little breathing space for its child elements). It is such a waste to implement this if the use case is only for desktop. You should also note that Nautilus core developer removed the treeview function due to this matter. A UIkit should be a starter framework that is usable to both situations (mobile and desktop). Therefore, something like this can easily be extended by using a third-party script. [You can start your research quest here](https://ourcodeworld.com/articles/read/146/top-5-best-tree-view-jquery-and-javascript-plugins).

**Comment by Nothing-Works** [comment]
@sudoranger  what's the alternative then?

**Comment by Diaskhan** [comment]
Imho very subjective answer from @sudoranger ! Not answer actually!  For mobile there might be no need to use treview ! But for desktop is ritorical question ! Every developer must decide by yourself!  Treeview is needed because enterprise software still use treeview ! Imho!

**Comment by sudoranger** [comment]
Then we all have to agree to disagree.

A lengthy drag operation in treeview is extremely error-prone; a tiny tremor on your index finger and files get dropped in the wrong place especially in a small touch-enabled devices like the Apple iPod.

Such contraversial decisions should always be left with user-customizable option but like I said earlier, the only way forward is to forget about treeview model. I get it that you are most probably missing Windows Explorer. Change is not easy, not to mention adaptation.

The design problem is a configuration panel (treeview) that takes up 1/3 the application space:
1. It's a desktop application (not web, not mobile)
2. Configuration groups have files which have child items that need to be seen/managed
3. There is a search feature, but no facets
4. Needs to be compatible with touch screens
5. The 1/3 width configuration panel directly affects the 2/3 width application area. The user needs to see the affects of their configuration choices live.
6. Imagine a worst case real world depth: 5-6 levels (groups can have sub-groups)

With that said, I don't like tree views, but sometimes they really are the most appropriate widget. Before you write the tree view off, it's worth thinking about whether it can be redesigned better for tablets.

Some issues with tree views:
- The drop-down icons are usually too small. They're hard to click even on desktops, let alone on tablets (see Fitt's law). (Idea: Can we make the icons larger?)
- Deep tree hierarchies occupy a lot of horizontal space, so you get clipping or horizontal scrolling, which is frustrating for users. Fortunately for you, you're intelligently budgeting 1/3rd screen space for this control so this is a bit less of an issue. (Idea: Can we use smaller indenting and line-wrapping to preserve horizontal space budget?)
- If the tree has many nodes, it's easy for users to get disoriented while deep inside the hierarchy.
(Idea: Can we use indicators to show what level of hierarchy we're at?)

@Nothing-Works This may or may not suit your needs, but I think it's always helpful to look at the possibility of modernizing an existing control before writing it off as antiquated. http://www.wpftutorial.net/Expander.html is what you might want to see. However, I believe that's Microsoft thingy and the date of that post is older than my grandmother.

@Diaskhan Back in 90's, there was only a few  available touchscreen smartphones, Desktop/PC dominated the world. It is about to change soon -- hence UIkit3 responsive framework. So yes, I guess my opinion is rather subjective. My last suggestion is: remember that for **enterprise applications**, the goal is usually to design the most **effective** interface, not the most **beautiful** one.

**Comment by Nothing-Works** [comment]
@sudoranger hahahaha you are so funny lol. I am not a designer, I have no idea. but I agree that treeview is really dated. It's like 20 years ago.

**Comment by Diaskhan** [comment]
In js world is hard to develop and mantain treeview !  Why name if framework ui kit.

Maybe it must be called ikit for ios ? 
It seems to me that  uikit is not js desktop ui !   Is ui kit for mobile))

**Comment by Diaskhan** [comment]
To sad. Ui kit is for hipsters)) that never want to use treeview )) and windows explorer must die with treeview for folders ))

**Comment by sudoranger** [comment]
@Diaskhan If you are going to argue over a topic at least give yourself a slight effort. You are only saying stuff like subjective, ikit, hipsters, and all other negative feedback without any real facts to support your idea on treeview. What makes you think UIkit as an ios or mobile-only framework? Please quote me so I can explain in simple English to avoid you insulting the community more.

Just because you want an ancient treeview model doesn't mean you can insult and label UIkit for hipster. If you read my first reply above, I've already suggested for you to start your research on 3rd-party treeview js or did you not do your homework and came here just to troll? If that so, we have no reason to continue this discussion anymore. Too bad for you, your creativity is only limited to a set of skills where such problems can actually be solved easily instead of begging to implement a feature you need in a hipster framework. How ironic?

Also, my last advice before you start using any front-end framework make sure you master vanilla html/css/js first. That way, you will not have to deal with such problem in the future. Good luck!

**Comment by Filipus24** [comment]
This thread is old, but here's my take on it:

while I do agree that treeviews are (mostly) a thing of the past reserved for desktop applications - where a mouse is more precise than a finger on a mobile device - I think it's important to remind everyone that frameworks like uikit are not solely for web pages or mobile development. I am referring more specifically to using the framework along with Electron, which allows me to design really effective - and beautiful - applications that will never be running on a mobile device.

In such cases, a treeview *may* very well be a useful component to have in a toolbox such as uikit.

There are plenty of code examples out there showing designers how to recreate Treeviews with CSS and JS, and I've done it a few times, but modifying those samples in order to integrate them seamlessly into an app that uses uikit is challenging. More than anything, I want my apps to have a uniform look and a consistent behavior. If there was a Treeview component whose look and functionality are consistent with that of the rest of the uikit framework, I would likely use it whenever it happens to be the most efficient for any given functionality my app requires.
