### ISSUE TITLE
mistake with tooltip when inside an off-canvas

### ISSUE THREAD

**Issue by cemfirat** [uikit/uikit#3869]
The link is in an off-canvas.
The off-canvas setting:
`uk-offcanvas = "flip: true; mode: push; overlay: false; bg-close: false"`

### UIkit version

3.1.5

### Browser
Safari Version 12.1.1 (14607.2.6.1.1)

### Reproduction Link

https://codepen.io/ccf/pen/pmrEvg

### What is actually happening?
The Title Attribute works as expected without (uk-tooltip):
`<a uk-icon="icon:crosshair-pointer;quote: 0.8" title="Hello World" href="#" class="uk-text-success uk-margin-small-left"> </a>`

The Title Attribute does not work as expected with (uk-tooltip):
`<a uk-icon="icon:crosshair-pointer;quote: 0.8" uk-tooltip="title: Hello World" href="#" class="uk-text-success uk-margin-small-left"> </a>`

**Comment by charlykwr** [comment]
I [see](https://codepen.io/CharlyKWR/pen/LYYVWMz) the same behaviour:

It comes to my attention that

- using title attribute instead of _uk_tooltip_ works fine (see _Menüpunkt 4.1.4_) but doesn't go well with UIkit's design,
- opening off-canvas produces a small scroll area in the upper right corner,
- a scrollbar is shown in this scroll area whenever the mouse hovers an item in off-canvas that have an _uk-tooltip_ attribute, but not when this item has a _title_ attribute (see also _Menüpunkt 4.1.4_),
- the tooltip of _Menüpunkt 1_ is shown correctly (tooltip is shown, no scrollbar).
