### ISSUE TITLE
uk-img native lazy support

### ISSUE THREAD

**Issue by TrilipuT** [uikit/uikit#3951]
Do you have any plans about changing/adding native lazy-load browser support with fallback?
Seems like Chrome moves forward with this...

https://web.dev/native-lazy-loading

**Comment by janschoenherr** [comment]
Yes, we are evaluating that.

**Comment by dramspro** [comment]
Hi all!
What about image preloaders in uikit 3.12+ ? I want use LQIP or low quality SVG preview, od SVG-animation as preloader while original image will be loaded. With old-style, pre 3.12 version UK-IMG i can made it, but now, as i see in announce, i cant set src and data-src with different values?

Native lazy loading is very low flexible, and cant provide full control of lazy loading!

And here other case, in article at [web.dev](https://web.dev/native-lazy-loading)  directly recommended usage of third-party JS solution (lazysizes as example), because image slider at first screen with "native lazy load" will be loaded fully, all images with no control, in pre 3.12 uikit i can preload 2 or 3 images or 1 but why we cant use uikit3 for lazy control anymore?
@janschoenherr @saschadube

**Comment by saschadube** [comment]
@dimasites In regards to the UIkit Slider, Slideshow, etc. They work great out of the box with native lazy loading in UIkit. Images will load lazy and the loading="lazy" attribute will be automatically remove from adjacent slides, so they will be immediately displayed.
