### ISSUE TITLE
Modal closes on drag & drop

### ISSUE THREAD

**Issue by JoeSixGo** [uikit/uikit#3963]
With an opened modal, any drag and drop operation that finishes outside the modal window trigger the closing of the modal. I don't know if this is the intended behaviour. To me it seems like a bug.

### UIkit version

3.1.9

### Browser
Chrome v76
### Steps to reproduce
Try to select some text inside the modal and release the mouse button outside the modal window

**Comment by Grawl** [comment]
still can reproduce on 3.2.0

**Comment by Lumelomser** [comment]
@janschoenherr 

Thanks for the fix!
Unfortunately, I have to tell you I just found another issue.

### Actual Behavior
Modal closes unexpectedly.

### Expected Behavior
Modal shouldn't close when clicking on an element, which isn't part of the modal DOM itself.
Modal should only close when clicking dark background layer.

### Reproduction Link
https://codepen.io/lumelomser/pen/oNXMEMe

### Steps to Reproduce the Problem
1. Open Link
2. Click "Open"-Button
3. Click "Drop"-Button
4. Click anywhere inside the opening Drop-Component

I'm familiar with the fact I could move the DOM of the dropdown into the modal itself.
I just give this as an example if an element is e.g. appended dynamically to the body tag or placed anywhere else outside them modal DOM.
