### ISSUE TITLE
dropdown doesn't close with href link as hash

### ISSUE THREAD

**Issue by wtfdanny** [uikit/uikit#3988]
### UIkit version

3.2.0

### Browser
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:69.0) Gecko/20100101 Firefox/69.0

Mozilla/5.0 (iPhone; CPU iPhone OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/19.0b16042 Mobile/15E148 Safari/605.1.15

Mozilla/5.0 (iPhone; CPU iPhone OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1

### Reproduction Link

https://codepen.io/44616e6e79/pen/mdboJgZ

### Steps to reproduce
Click a link within a dropdown menu with a hash set in `href`

### What is Expected?
Dropdown should hide itself

### What is actually happening?
Dropdown remains visible

This was fixed originally in #3798

**Comment by Morrison52** [comment]
Add `uk-dropdown-close` class to your url to close the dropdown or use `UIkit.dropdown(element).hide();` js. Your issue will conflict with #3952 and more bad than your issue since will break the navigation (accordion) on multiple websites where using anchor links (hash).
Reproduction link: https://jsfiddle.net/72u164wL/

**Comment by wtfdanny** [comment]
Thanks for the suggestion @Morrison52 !

**Comment by Morrison52** [comment]
Welcome, does it is solve your problem? If yes can you close this issue?

**Comment by wtfdanny** [comment]
I just verified that it does. Closing.
