### ISSUE TITLE
Offcanvas doesn´t close anymore after click on link with `uk-scroll` ( uk-offcanvas-close adds undesired styles )

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#4001]
### UIkit version

3.2.1

### Browser
All
### Reproduction Link

https://codepen.io/zzseba78/pen/NWWGYxR
### Steps to reproduce
Click button to open Offcanvas, click on Offcanvas button to scroll to footer.
### What is Expected?
Offcanvas close ( as previous version does )
### What is actually happening?
Offcanvas doesn´t close.

It worked until v3.1.7 
https://codepen.io/zzseba78/pen/PooPRzq

**Comment by Morrison52** [comment]
Because you use hash/anchor will not close the offcanvas, a link with hash/anchor will break the navigation with accordion in offcanvas where was a issue in [3952](https://github.com/uikit/uikit/issues/3952).
You can add `uk-offcanvas-close uk-position-relative` class or use `UIkit.offcanvas(element).hide();` js to close the offcanvas.
Reproduction Link: https://codepen.io/Morrison52/pen/eYYpbwN
Small note: There is a bug in jsfiddle, with position relative the padding is ignored and you need to set the position to initial or unset.

Does it solve your problem, if yes can you close?

**Comment by zzseba78** [comment]
@Morrison52 First of all, thanks for your response.
Ok, i get it, some observations:

- The `uk-offcanvas-close` class shouldn´t apply styles to the element, and only close the offcanvas. It adds position absolute, top and right position and padding, of course you can overwrite them, but it´s not clean implementation.

- Links with `uk-scroll` or `data-uk-scroll` means to scroll the page, so makes sense the offcanvas close on links with this attributes.

**Comment by janschoenherr** [comment]
You can give your Offcanvas another selector for the close action, e.g. `selClose: .my-close-class`

**Comment by zzseba78** [comment]
Great! thanks.
