### ISSUE TITLE
Tooltip and Modal z-index issue

### ISSUE THREAD

**Issue by papazetis** [uikit/uikit#4014]
### UIkit Version
3.2.2

### Actual Behavior
Tooltip on top of modal on mobile

![Screenshot](https://user-images.githubusercontent.com/3592665/67530261-75106400-f6b6-11e9-930b-5d016db0fbb2.png)

Current uikit z-index property is:

```
.uk-tooltip {
   z-index: 1030;
}
```

```
.uk-modal {
   z-index: 1010;
}
```

**Comment by eljass** [comment]
This can be fixed by setting the tooltip option `container` to the modal component. Then appearing tooltip element is positioned inside the modal and the z-index 1010 is relative to the modal's content.

Example: If you have only one modal you can use class .uk-modal, but in case there are multiple modals I recommend setting a unique id attribute to each of them.

`uk-tooltip="container: .uk-modal;"`

or

`uk-tooltip="container: #modal-id;"`
