### ISSUE TITLE
Custom prefix

### ISSUE THREAD

**Issue by idkoukou** [uikit/uikit#4026]
Hi Friends.
I just want to know how to use this command `yarn prefix -- -p xyz` and in which folder to customize the prefix.

**Comment by joeyslack** [comment]
What are you trying to do? It sounds like `prefix` might not be doing what you think it is. In node, prefix is used to set the execution path prefix, is that what you're trying to do?

Doesn't sound like a UIKit issue.

**Comment by stivoox** [comment]
@joeyslack I'm talking about this : https://getuikit.com/docs/avoiding-conflicts . 
Documentation : **for example xyz-grid instead of uk-grid. The global JavaScript object UIkit will also be renamed to xyzUIkit**

**Comment by joeyslack** [comment]
@stivoox Oops, you're right. Looks like it worked for custom build. Should work for you if you clone the repo, run a build, then run the command.

**Comment by bdthemes** [comment]
custom prefix not working again 😭 

I followed the doc, it's working before 3.5.4

Now the problem is:

when I run this command: `yarn prefix -- -p bdt`

![image](https://user-images.githubusercontent.com/2105615/93514882-89ea8b80-f949-11ea-873d-ce48289165a3.png)


it changed the main uikit object
![image](https://user-images.githubusercontent.com/2105615/93514090-96baaf80-f948-11ea-84b3-5994504c6a5e.png)

but not all uk- prefix in others lines

![image](https://user-images.githubusercontent.com/2105615/93514402-fc0ea080-f948-11ea-9a9b-2f4013fb7d6f.png)

![image](https://user-images.githubusercontent.com/2105615/93514549-29f3e500-f949-11ea-9216-e832c879469c.png)


What should I do?

How to replicate the issue?

Just pull the latest 3.5.7 then try to change the prefix

**Comment by janschoenherr** [comment]
This seems to be resolved.
