### ISSUE TITLE
I am needing something that targets resolutions for mobile devices.

### ISSUE THREAD

**Issue by mrmoodoo** [uikit/uikit#4058]
Example: `/* Smartphones (portrait and landscape) ----------- */ @media only screen and (min-device-width : 320px) and (max-device-width : 480px) { /* Styles */ }`. Right now, UIkit 3 only allows for 640px and larger (uk-width-*@s - Affects device widths of 640px and larger. Grid columns will stack on smaller sizes. source: https://getuikit.com/docs/width#responsive-width). Maybe it should be 640px and smaller? Am I misunderstanding how to use this feature?

**Comment by mattfletcher** [comment]
You are misunderstanding how the system works. Think of it as a mobile-first system. For example, if you want a section of your site to be 2-across on mobile, but 4 across on bigger devices, then you would use a class set like: "uk-width-1-2 uk-width-1-4@s". 

There aren't styles targeting devices smaller than 650px (or whatever the smallest breakpoint is) because they are catered for by the default ones.

**Comment by mrmoodoo** [comment]
Thanks @mattfletcher, I see now, thanks. I guess for me the semantics were a little confusing.
