### ISSUE TITLE
Accordion "Cannot read property 'parentNode' of null"

### ISSUE THREAD

**Issue by incohe** [uikit/uikit#4073]
hi i created an accordion dropdown menu when my nested <ul> <li> is in the last part (2nd level accordion last child) of the menu and i make it as an accordion im having an error "Cannot read property 'parentNode' of null" in developer console. even in the latest build the issue still remain

tested version 3.1.5 to 3.2.6 

![image](https://user-images.githubusercontent.com/55270275/71498349-f8a52780-2896-11ea-8507-578263c160da.png)
![image](https://user-images.githubusercontent.com/55270275/71498364-08247080-2897-11ea-9e3a-8676b2ac3c22.png)
error happen in the last li (events)

**Comment by eatinsnacks** [comment]
I also just ran into this issue.

**Comment by eatinsnacks** [comment]
@incohe this happened to me and it was because there was a script tag in between my accordions. I looked at your code and it looks like your spans aren't being properly closed. I _think_  I'm seeing more open than close. It's hard to tell from an image.. but if that's happening then it will throw off the accordion content. I'm seeing on line 2, 2 spans open but one closes. You need to close it after the product title or after the icon. This is happening again on line 5.
