### ISSUE TITLE
Slider issue when scrolling down (Chrome only?)

### ISSUE THREAD

**Issue by jlahijani** [uikit/uikit#4205]
### UIkit Version

3.4.6

### Actual Behavior

I have a slider.  When it is animating to the next slide AND I scroll down, the page jitters and I can't successfully scroll down until the animation is complete.  It seems to be happening only in Chrome.  I tried a bunch of other things related to the page, including removing the sticky navbar, disabling all 3rd party plugins, disabling all slider options, but the issue remains.  I also tried putting the slider in a container, showing multiple sliders at once.

Video demonstrating the issue:
https://www.youtube.com/watch?v=agGGMBNkYR8

This might be related?
https://github.com/uikit/uikit/issues/4071 

### Expected Behavior

It should scroll down normally.

**Comment by SuperKrevette** [comment]
Oulala. The hell is that?

**Comment by lonewsk** [comment]
Got the same problem here.

Hence my video:
[https://youtu.be/AGsyzBSsKXo](https://youtu.be/AGsyzBSsKXo)

**Comment by adleviton** [comment]
Similar problem in Google Chrome, but OK in Firefox. I can't scroll the page when using animations that alter position (e.g. uk-animation-slide-top, uk-animation-scale-down, etc.).

If I resize my browser window, the problem goes away.

Example: https://www.dropbox.com/s/envm767lg9m7yrp/Screen%20Recording%202020-06-28%20at%206.41.10%20PM.mov?dl=0

**Comment by viocassel** [comment]
Confirm!

**Comment by sahilNR** [comment]
Seems like it is caused by [this](https://github.com/uikit/uikit/blob/develop/src/js/core/core.js#L11) `scroll` `eventListener` on `window`. When I manually remove it from Chrome dev console, the jitter effect goes away.
 It's not just on the slider. I had a section with my custom css animation applied to some elements. It was doing the same thing. 

https://github.com/uikit/uikit/blob/develop/src/js/core/core.js#L11

**Comment by csaggo** [comment]
same problem here on android chrome we have a slider on the top and one can not sucessfully scroll down

**Comment by adleviton** [comment]
My issue described above was due to using **uk-sticky**.

I had an element with uk-sticky that was hidden on larger screen sizes via `display: none;`

Instead, I used the following CSS to hide the element and problem solved:
```
z-index: -1
visibility: hidden;
```
It now makes sense that any issues related to scrolling would involve uk-sticky and/or uk-scrollspy … I should have checked there first!

**Comment by jlahijani** [comment]
> My issue described above was due to using **uk-sticky**.
> 
> I had an element with uk-sticky that was hidden on larger screen sizes via `display: none;`. And this caused the stuttering scroll behavior.
> 
> Instead, I used the following CSS to hide the element and problem solved:
> 
> ```
> z-index: -1
> visibility: hidden;
> ```
> 
> It now makes sense that any issues related to scrolling would involve uk-sticky and/or uk-scrollspy … I should have checked there first!

Ahh! Yes this is the issue for me too.  I have a desktop navbar and a separate mobile navbar, both which were uk-sticky. Removing uk-sticky from the mobile navbar fixed the issue.

YooTheme Pro is also setup to have separate desktop and mobile navbars.  I think this definitely should be fixed.

**Comment by janschoenherr** [comment]
We've improved the sticky component to stay inactive if hidden. Can you please check the latest dev build to verify?

https://www.jsdelivr.com/package/npm/uikit?version=3.5.6-dev.edf774a0a

**Comment by adleviton** [comment]
I'm still seeing the same issue.
