### ISSUE TITLE
Space cannot be entered to search input followed by uk-dropdown

### ISSUE THREAD

**Issue by strepon** [uikit/uikit#4560]
If there is a combination of search input and dropdown, e.g.:
```
<form class="uk-search uk-search-default">
  <input class="uk-search-input" type="search" />
  <div uk-dropdown></div>
</form>
```
it is not possible to enter the space character into the search input, because the space key is used to toggle the dropdown - which makes searching unusable.

See it in action here: https://codepen.io/strepon/pen/jOGvgKR

This behaviour was caused  by this fix of keyboard navigation (between 3.7.3 and 3.7.4): b784cd81192200b24e4e082af83915539c09c8c1

If this is expected, then at least a note should be added to the documentation as now it says that ["Any content, like a button, can toggle a dropdown"](https://getuikit.com/docs/dropdown).

**Comment by dominikfiala** [comment]
Just encountered this issue too. I see no reason why should space key emmit a button click. Makes no sense. Especially because a lot of us use a combination of text input and dropdown to create a search suggest component.

Also I noticed that using dropdown `mode: hover` is not affected.

See extended demo https://codepen.io/dominikfiala/pen/mdBaPqx

**Comment by strepon** [comment]
Great, thanks for the modification! Confirming that now it works again.
