### ISSUE TITLE
Please add a threshold setting for slider

### ISSUE THREAD

**Issue by BernhardBaumrock** [uikit/uikit#4665]
### Summary

The Problem: I have a slider for quotes. Today when testing my design on mobile I wanted to scroll down to read the whole quote (it was a lot of text), but my finger moved slightly to the left, which caused the slider to swipe to the next item.

This is obviously not what I wanted, because I wanted to read the last part of the current quote - not the next one.

Could you please add a "threshold" setting, so that, for example the slider jumps only to the next item in case the threshold is exceeded. Not sure what the best unit for that would be, maybe something like "30vw"?

TailwindCSS has a similar concept using "snap": https://tailwindcss.com/docs/scroll-snap-type

### Priority

High - In my opinion this is very bad UI and a slider is a very basic component that almost any site has.

**Comment by viocassel** [comment]
+1

**Comment by haeki1** [comment]
Hi,

I guess that issue is not completely solved. I do use YoothemePro and tested the beta version which is using Uikit 3.16.15. Especially when autoplay is active and you do not exactly scroll vertically on mobile it swipes only the slider and the user is kind of stuck above the fold. That might result in a user leaving the page. I tried to play with threshold in **line 7097** but had no success.

`var SliderDrag = {
      props: {
        draggable: Boolean
      },
      data: {
        draggable: true,
        threshold: 10
      },`

Here is the example, slider is right at the top: https://ytp4.helloworldstudios.com/sample-page/

Kind regards
