### ISSUE TITLE
Timeout in Slider when loading WebP

### ISSUE THREAD

**Issue by ts0924** [uikit/uikit#4966]
### UIkit Version

_Check if the issue is reproducible with the latest stable version._
3.18.0

### Actual Behavior

Timeout or loading status forever when reading images as slider items.

### Expected Behavior

Loading completed and slide items are shown. It was OK till 3.17.11.

### Steps to Reproduce the Problem

1. Timeout when loading WebP in uk-sider > uk-slider-items
2. JPEB/PNG is fine

**Comment by santo74** [comment]
I'm having the same issue with WebP images in a slider.
Other sliders on the same site that use jpg images instead of WebP work as expected.

**Comment by janschoenherr** [comment]
It seems to work fine for me, can you please add a minimal codepen example?

**Comment by santo74** [comment]
@janschoenherr I found the cause of the issue.
I tried to create a reproducer in codepen as requested, but without success.
Therefore I knew something was different between the codepen and my code, although the html was an exact copy/paste.
After reinvestigating the website where I noticed the issue, I detected that an older version of the uikit.min.js file was being served because of some inheritance issue with a parent template.
After fixing that, the correct version of the js file was loaded and the slider with lightbox worked as expected.
