### ISSUE TITLE
UIkit modal is not working for static raw HTML  |  UIkit.modal(element).show();

### ISSUE THREAD

**Issue by maudud-bdthemes** [uikit/uikit#5032]
### UIkit Version

_Check if the issue is reproducible with the latest stable version._
3.21.6

### Actual Behavior

Not working from version 3.20.0, for example: https://codepen.io/maudud/pen/qBzOpGP

### Expected Behavior

It was working on version 3.19.4, for example: https://codepen.io/maudud/pen/RwzWxey

### Reproduction Link

https://codepen.io/maudud/pen/qBzOpGP

### Steps to Reproduce the Problem

1. I use this code: https://drive.google.com/file/d/151pA7MnJNbjAi5UO7dOAXNXxy8_l5sZ2/view?usp=sharing

**Comment by dobaniashish** [comment]
This happens because component now uses `findAll` instead of `$$` util function as it did before.

`findAll` function expects the first parameter to be a selector or element and not raw html.

Until this issue is considered by UIkit team, you can use `fragment` or `$$` util functions while passing the element.

```
UIkit.modal(
  UIkit.util.fragment(
    '<div id="modal-close-default" uk-modal><div class="uk-modal-dialog uk-modal-body">test</div></div>'
  )
).show();
```

**Comment by maudud-bdthemes** [comment]
Thanks for the quick response!
