### ISSUE TITLE
Animation component does not work in this Toggle/Modal case

### ISSUE THREAD

**Issue by juanrpop** [uikit/uikit#5036]
`animation: uk-animation-fade` in `uk-toggle` does not work when `cls: uk-hidden` is applied to `uk-toggle`, instead of `hidden` attribute.

`cls: uk-hidden` has been added to the `<p>` content within `uk-modal` so toggling (inside the modal) works correctly.

See the codepen here: [codepen.io/juanrpop/pen/qBzZpXE](https://codepen.io/juanrpop/pen/qBzZpXE)

**Comment by dobaniashish** [comment]
Hello @juanrpop,

I think we are back at Issue #5035 

Until the issue is considered by UIkit team, you can extend the toggle component by refactoring `isToggled` function to use `hasAttr` util function instead of `Element.checkVisibility()`. I hope this workaround helps.

Check this codepen https://codepen.io/dobaniashish/pen/XWLdwMX

@janschoenherr, I would like to provide a pull request if the above solution is considered to be correct and does not effect other uses of `togglable` mixin.

**Comment by juanrpop** [comment]
Hi @dobaniashish, thanks for your time. Yes, we are back on topic #5035.

I have implemented your solution and as far as I know, your code does not break anything.

Nonetheless, I do get a flickering animation. You can view my implementation here: https://codepen.io/juanrpop/pen/GRbqYgv 

I am by no means a JS expert, and it is entirely possible that I am implementing your solution poorly (below the local script `uikit.min.js`, I simply add a new line of `script:src` code in the HTML file).

Thanks again for your help.

**Comment by janschoenherr** [comment]
There would be a "hacky" workaround: 

```
    <a
      href="#"
      uk-toggle="target: .toggle; cls: a uk-hidden; animation: uk-animation-fade"
      >TOGGLE</a
    >
    <a href="#modal" uk-toggle>MODAL</a>
    <p class="toggle a">Content A</p>
    <p class="toggle uk-hidden">Content B</p>
    <div id="modal" uk-modal>
      <div class="uk-modal-dialog">
        <p class="toggle a">Modal Content A</p>
        <p class="toggle uk-hidden">Modal Content B</p>
      </div>
    </div>```

Now `a` is the defining class, the toggle component checks against. Currently we don't have a good way to define, which is the `none-active` class.

**Comment by juanrpop** [comment]
@janschoenherr Thank you for answering, works fine.
