### ISSUE TITLE
uk-disabled class in forms

### ISSUE THREAD

**Issue by zslabs** [uikit/uikit#697]
Looks like `uk-disabled` is an available class in the sub-nav and pagination component, but think it'd be a great addition to add-in for the form -- the current `readonly` attribute doesn't change the styles enough to let someone know they can't enter anything.

**Comment by zslabs** [comment]
Any progress on this one?

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. We added a global class `uk-disabled` within UIkit3. This will not add the style of a disabled button since it can be used for every link button or form item, instead it just removes the click events. 

Thanks for your understanding,
Your UIkit Team
