### ISSUE TITLE
need uk-width-mini & uk-hidden-mini

### ISSUE THREAD

**Issue by mygoare** [uikit/uikit#735]
uk-width-small & uk-hidden-small are still not small enough for mobile phone devices. 

On the [uikit compontents page](http://getuikit.com/docs/components.html), there is a Mini Breakpoint there, but it seems not be deployed yet.

**Comment by safrick** [comment]
+1 for uk-width-mini-*

**Comment by philoest** [comment]
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. We haven't added a mini breakpoint here, instead we added a xlarge. But with your custom styles you can easy modify the breakpoints that way that the small breakpoint is your mini, so that the four breakpoints fit your needs.

Thanks for your understanding,
Your UIkit Team
