### ISSUE TITLE
Themes on bower distribution

### ISSUE THREAD

**Issue by Garfield-fr** [uikit/uikit#798]
Hi,

It's possible to make the theme folder (almost-flat, gradient) with less and sass files in bower distribution.

Thanks

Bertrand

**Comment by saschadube** [comment]
We are torn about it. Why do you need this? Don't you have your own theme? Just copy one of the existing...

**Comment by zslabs** [comment]
Hey @saschadube,
Appreciate the reply. The easiest way for me to explain the reasoning is how UIkit is used in my typical setup as an abbreviated example:

		// app.less

	/* 1
	I pull in the core button component from UIkit */
	@import "/bower_components/uikit/src/less/button";

	/* 2 
	Since the core doesn't provide any sensible defaults for global variables, 
	I pull the almost-flat version of the button component to give me some global 
	variables to work with */
	@import "/bower_components/uikit/themes/almost-flat/button";

	/* 3 
	If I then have project specific overrides for the button component, I create 
	a button.less file in a uikit folder in my src files to keep the logic of what's 
	interacting with UIkit and what's my custom styles separate for clarity */
	@import "uikit/button";

	/* 4
	Any custom styles that are not UIkit specific go here */
	@import "global";

As you can see, I have a "multi-layered" inheritance system going on here. Why don't I just copy over `almost-flat` and build from there? Simple, to keep my sanity. I'm one for keeping up to date with UIkit as it changes and evolves. If I were to copy over the `almost-flat` theme over to my own folder, then when an update occurs, I'll have a mess to go through to figure out what vars were changed or added specific to that theme, instead of inheriting from sane defaults.

This is just another example of why the `default` theme should be in the core. Think about how much smaller `gradient` and `almost-flat` would be if they don't "re-override" core variables that should be globalized by default, and only include the UI elements they need to override. Also maintenance of not only these separate themes, but your WordPress & Joomla products would be dramatically simplified because you wouldn't be reinventing the wheel each time.

If that was done, then there'd be no need to add themes to the bower distro, because sane defaults would already be there. This next part is only said as an example, but it's for good reason that Bootstrap and Foundation do this by default -- it's because the layer of complexity that is added by having this core setup with no real-use of the power of LESS turns into a dependency nightmare.

I sincerely hope you consider the comments above in hopes of a natural progression of making UIkit have saner, smarter defaults with not only just end-users, but maintenance to all parties involved much easier. Thanks as always.

**Comment by mcraiganthony** [comment]
+1000 Zach

**Comment by Garfield-fr** [comment]
I agree with @zslabs

**Comment by uikid** [comment]
The workflow of @zslabs helped a bit, but I'm not quite sure how to implement a theme with all the .less files like the creators thought it. What is best practice there?

**Comment by zslabs** [comment]
@saschadube To further drive the point home here, in its current state, the core/theme/custom level inheritance is causing a high barrier to entry for my team because they are coming from  Foundation/Bootstrap. And like I mentioned previously, would DRAMATICALLY reduce the size and effort of what you have to do for your theme (products) through YooTheme.

**Comment by zslabs** [comment]
This something I can jump on to get it knocked out? This would dramatically reduce the footprint of customizations from the framework. If we start with smarter defaults, then customizing can become as generic OR granular as the project requires. 

Again, even if we look at this from a business perspective, YooTheme themes would be that much easier to maintain as newer versions of UIkit are released. They become more "patches" than rethinks if there are breaking changes.

**Comment by krzksz** [comment]
+1 to this. Being able to choose or exclude even the default visual theming(things like `border-radius`, `box-shadow`, `background` and even `color` should go there) would drop the number of things I have to overwrite down dramatically, `default.less` could just be imported in `uikit.less` file and things would stay the same for default.

**Comment by adaedra** [comment]
+1

It'd allow to depend on a theme without having to copy everything manually and allow to track new versions of the themes as easily as you do with main uikit.

Is it something still in discussion?

**Comment by zslabs** [comment]
I've reached out a few times, but nothing that has been cemented. Really believe this is a wider-adoption issue... and I don't mean in a good way. Am MORE than happy to help get this rolling; it just has major implications for their WordPress/Joomla themes -- meaning they could potentially re-work the variables in there, but for an overall better product.

**Comment by mariusc23** [comment]
I had the same issue but I managed to resolve it by installing the uikit repository instead. **Note**: You might have to delete the existing `uikit` folder in `bower_components` first.
```bash
bower install uikit/uikit --save
```
You should see something like this in `bower.json`:
```json
"uikit": "uikit/uikit#~2.20.3"
```
Then you can import the almost-flat theme:
```less
@import 'uikit/themes/almost-flat/uikit';
```
+1 for including them in the bower distribution though.

**Comment by adaedra** [comment]
This works as long as you're using LESS. The main repository doesn't have the SCSS version.

**Comment by adamwoodnz** [comment]
+1 would make our sass pipeline much simpler

**Comment by chiefie** [comment]
+1 too.

**Comment by blissini** [comment]
+1

**Comment by zslabs** [comment]
@saschadube @aheinze Any updates on where we stand with this? From the first few articles about UIkit - it's all about giving the most value with the smallest footprint, and making these smart defaults would be a huge step for the framework.

**Comment by giovannicandido** [comment]
+1

**Comment by digitaljhelms** [comment]
Over a year without so much as a response? Impressive...

**Comment by manuelh9r** [comment]
+1

**Comment by petermumford** [comment]
Having the almost-flat theme in the SCSS bower distribution repo would be great for me too. Will save a huge amount of time!

**Comment by thomasfw** [comment]
+1

**Comment by idolab** [comment]
+1.
Using scss does not mean we want to customise it from the ground up

**Comment by elasticsteve** [comment]
+1 If you want this framework to go anywhere -> absolutely essential!

For example, I only want to adjust a few things in the gradient theme with SASS. Right now it's a nightmare! Stuck with the css, where I have to override things in a million places! -> BAD

**Comment by davidkhess** [comment]
FYI, somebody forked and ported the almost flat theme to SASS here:

https://github.com/cpannwitz/uikit/tree/develop/themes/almost-flat-sass

**Comment by philoest** [comment]
Hi everyone, this will be added in UIkit3 as soon as the SASS is ready :)
