### ISSUE TITLE
Datepicker Docs Don't Explain 'update.uk.datepicker'

### ISSUE THREAD

**Issue by thealexbaron** [uikit/uikit#884]
I was able to listen on the `change` event even though it's not listed in the docs. This event is vital.

**Comment by vuchl** [comment]
You are right, that the date picker is not firing an event. This is due to the fact that it is using the autocomplete component. But I guess it would be the right call to ask for some date picker events like `show.uk.datepicker`, `hide.uk.datepicker` and `update.uk.datepicker`.

@aheinze Maybe you guys could take this into consideration.

**Comment by aheinze** [comment]
it is an input element. the change event is always triggered if the value changes. I don't know if it is something needed to extra document.
