### ISSUE TITLE
Form validation classes remove user set background images 

### ISSUE THREAD

**Issue by jammnrose** [uikit/uikit#894]
In `form.less` the rules for form validation states look like:
```
.uk-form-danger {
    border-color: @form-danger-border !important;
    background: @form-danger-background !important;
    color: @form-danger-color !important;
    .hook-form-danger;
}
```
In my application CSS (LESS) I'm setting a small background image on a few of my form fields, but this image gets removed when validation classes are active.

I think it would make more sense to have the UIkit form validation classes only set the `background-color` property, so as not to step on the toes of people who may be using other `background-*` properties.

**Comment by saschadube** [comment]
Thanks, good idea! But we don't want to change it at the moment because it could break current themes (for example if gradients are used). We will definitely consider it for UIkit 3. Please suggest it [here](https://github.com/uikit/uikit/issues/560). For now, please do a work around in your UIkit theme.
